### ISSUE TITLE
[BUG] Move Extruder up instead of left upper corner after mmu load/unload fail

### ISSUE THREAD

**Issue by fpvdoc** [prusa3d/Prusa-Firmware#2993] opened 2021-01-25 00:17 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK3S 
**Printer firmware version**-  3.9.3

**MMU Upgrade** - MMU2S
**MMU upgrade firmware version 1.0.6

**SD card or USB/Octoprint**
USB/Octoprint

**Describe the bug**
After a load/unload failure, with no sparse layers being enabled, the extruder moves to the left corner at the height of the purge block or a little higher but not above the printed part. That can cause a collision with the part even though the slicer doesn't detect a collision in slicing.
  
**To Reproduce**
Find the picture attached, because of file size limitation neither gcode nor 3mf can be uploaded.
  
**Expected behavior**
 The extruder should just move up from the purge block but not to the left side. This will greatly increase build volume with no sparse layers being enabled.
  
Unfortunately the gcode or 3mf file is too big to upload. Please find the picture attached, it pretty much clarifies what I'm talking about.
![IMG_7428](https://user-images.githubusercontent.com/54080049/105648238-b9d30e00-5eaa-11eb-8276-a53e63435d15.jpg)

**Comment by JohnnyDeer** [comment] 2021-02-04 11:20
Hi @fpvdoc, this issue is duplicate of #2540, I´m closing.

**Closed as completed by JohnnyDeer** 2021-02-04 11:20 UTC
Labels: bug
