### ISSUE TITLE
[BUG]<Printer is hitting model during filament replacement>

### ISSUE THREAD

**Issue by Szpansky** [prusa3d/Prusa-Firmware#4693] opened 2024-05-24 10:51 UTC
**Printer type** - [e.g. MK3S]
**Printer firmware version** -  [3.13.3.]

**SD card or USB/Octoprint**
Octoprint

**Describe the bug**
I have sequence output setting 'on'. During filament replacement to the next fresh spool, the printer crashes to the previous model.
The printer was out on 1st layers and the printer should go higher on the Z axis.
After the filament replace the printer starts printing in a different place due to the crash.
  
**To Reproduce**
Set sequenced output,
print one model in front of the printer at least 30mm high, it should be more on the right side of the bed.
cut the filament when the printer starts printing the next model to see how the printer is hitting the previous model during filament replacement.
  
**Expected behavior**
The printer should know the exact height to move so, as to not hit the previously printed model if we run out of filament.
  
**G-code**
n/a

**Video**
Photos:
![c8cb3f7c-99bd-4657-b5f1-d170800b01ee](https://github.com/prusa3d/Prusa-Firmware/assets/16843612/1cf33da5-8770-49d1-bf67-647e3088fd49)
![135da05e-7925-4625-8f75-c94009a205b5](https://github.com/prusa3d/Prusa-Firmware/assets/16843612/9d420006-852c-446d-865e-8aab90706fab)
![b2027210-be65-48fe-a9ef-ce652a54dac4](https://github.com/prusa3d/Prusa-Firmware/assets/16843612/ff47ffc1-9341-4f83-8609-418f20a170b7)

**Comment by 3d-gussner** [comment] 2024-05-24 11:43
@Szpansky This is a duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/3496

We are looking into that issue. Sequential prints are bit challenging in this regard.

Please consider to close this issue.

**Closed as completed** 2024-05-24 13:15 UTC
Labels: bug, duplicate
