### ISSUE TITLE
[BUG] "File Incomplete" message incorrect

### ISSUE THREAD

**Issue by dhouckii** [prusa3d/Prusa-Firmware#4546] opened 2023-12-19 21:48 UTC
**Printer type** - MK3S
**Printer firmware version** -  3.13.2

**MMU upgrade** - MMU3
**MMU upgrade firmware version** - 3.0.1

**SD card or USB/Octoprint**
  SD Card

**Describe the bug**
  The check for M84 to see if the file is complete needs to ignore commented out lines.  Based on my research, it looks like the firmware checks the last 20000 bytes.  With the new features in PrusaSlicer, there many comments at the end of the file that are more than the 20K characters. 
  
**To Reproduce**
  Slice any print with 5 colors and look at the resulting GCODE and you will see the plethora of comments at the end that push the M84 command too far up in the file.
  
**Expected behavior**
  No error message be generated when starting the print.
  
**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.
[gingerbread_ornament_0.2mm_PLA,PLA,PLA,PLA,PLA_MK3SMMU2S_3h20m.gcode.txt](https://github.com/prusa3d/Prusa-Firmware/files/13720678/gingerbread_ornament_0.2mm_PLA.PLA.PLA.PLA.PLA_MK3SMMU2S_3h20m.gcode.txt)

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by 3d-gussner** [comment] 2023-12-20 05:30
@dhouckii Thanks for reporting this issue and very well filled out template, very appreciated.
>Based on my research, it looks like the firmware checks the last 20000 bytes.

Great to see that you searched yourself what could be the cause before opening this issue bug report.

The previous issues reporting this have been closed so finding these isn't easy. See #2328 and #4506

This has been already addressed with https://github.com/prusa3d/Prusa-Firmware/pull/4507 and will be in next firmware release.
Please consider to close this.

BTW nice gcode and you even selected matching colors for the preview.

**Closed as completed** 2023-12-20 05:52 UTC
Labels: bug, duplicate
