### ISSUE TITLE
[FEATURE REQUEST] Enforcing Re-Homing as if there was a crash

### ISSUE THREAD

**Issue by moboch** [prusa3d/Prusa-Firmware#3035] opened 2021-02-18 17:07 UTC
I think it would be a really good addition the be able to enforce the re-homing during a print, just as if a crash happened. This could either be used in stealth mode where crash detection is unavailable and you notice a skipped step so you can rescue the print, or when a skipped step happens and the crash detection doesn't register it. The menu option could be called something like "Reset Position" and would be accessible while a print is paused.

**Comment by vintagepc** [comment] 2021-03-03 13:02
FYI there is already an open PR/feature request for this. 

https://github.com/prusa3d/Prusa-Firmware/pull/2474 and #2161

**Comment by Prusa-Support** [comment] 2022-06-02 18:11
Thanks for sharing your idea.

This issue is actually a duplicate of issue #2161 mentioned above and it will be closed as such.
Please check this issue and possibly refer to it in case of future discussions.

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2022-06-02 18:11 UTC
Labels: duplicate, feature request, HW issue, troubleshooting, crash
