### ISSUE TITLE
[BUG] Bed starts heating when selecting unload filament.

### ISSUE THREAD

**Issue by GMeyerGMeyer** [prusa3d/Prusa-Firmware#3709] opened 2022-10-19 17:41 UTC
--> MK3S, 3.11, no MMU, Sd card,

As described, when i want to unload Filament, i do not need to heat the bed. But in fact, the printer does it. 

Wanted behaviour: When unloading Filmanet (PLA), do not start heating the bed. Just heat the nozzle. Thanks. 

Cheers George

**Comment by neophyl** [comment] 2022-10-20 06:49
Duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/422

**Comment by Prusa-Support** [comment] 2022-10-20 08:47
Hello, thank you for the post, I confirm it's a duplicate of #422, this enhancement is being discussed with devs, nothing is promised but perhaps there might be a future change. Closing this particular thread being it duplicate, but feel free to add more comments on the #422 thread. Thank you. 

Alessandro Pantaleo
Prusa Research

**Closed as not planned by Prusa-Support** 2022-10-20 08:47 UTC
Labels: duplicate
