### ISSUE TITLE
[FEATURE REQUEST] Preheat option for nozzle changes

### ISSUE THREAD

**Issue by Hobbiticus** [prusa3d/Prusa-Firmware#2992] opened 2021-01-24 15:45 UTC
This goes along the lines of this request:
https://github.com/prusa3d/Prusa-Firmware/issues/2972

A quick and dirty solution is to add a preheat option for nozzle changes.  I have made the modifications necessary in the firmware for my use, so I figured I'd share it for others to use or to be incorporated into the baseline firmware.

This will simply add another entry in the preheat option called "NCHG" (for nozzle change, obviously) that will heat the nozzle to 285C and bed to 0.  This prevents having to remember that 285 is the magic temperature for nozzle changes and having to spin the nozzle temperature all the way up to 285, which takes a fair amount of time.

That said, it would still be nice to incorporate this into a nicer nozzle change sequence as described in issue 2972 (linked above).

Diff from 3.9.3 tag:
[nozzle_change.diff.txt](https://github.com/prusa3d/Prusa-Firmware/files/5862546/nozzle_change.diff.txt)

**Printer type** - [e.g. MK3S, MK3, MK2.5S, MK2.5, MK2S, MK2]
All Prusa FDM printers

**Comment by Prusa-Support** [comment] 2022-07-19 15:51
Thanks for the suggestion.

This issue could be actually closed as a duplicate of issue #2972.
If the idea behind this post is offering a fix to the already discussed issue, please consider opening a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests).

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2022-07-19 15:51 UTC
Labels: feature request, HW issue, temperature, materials
