### ISSUE TITLE
M702 Unload raises extruder too much

### ISSUE THREAD

**Issue by timur-tabi** [prusa3d/Prusa-Firmware#3532] opened 2022-07-04 20:16 UTC
MK3 upgraded to MK3s
3.11.0-4955

When I ask my printer to unload the filament, first it raises the extruder.  IMHO, it raises the extruder too much, perhaps about 4-5cm.  This often puts the extruder close to the of top the Z-axis, making it harder to load new filament.

I'm pretty sure that this is a change during the last year or so.  When I first got my MK3, it only raised the extruder about 2cm, which is much more reasonable.

**Comment by wavexx** [comment] 2022-07-09 12:35
Yes, we indeed increased the unload raising distance to make unloading easier when Z is low since it's more convenient to clean the nozzle in that case.

I fail to see how raising close to the top makes it any harder though?

**Comment by timur-tabi** [comment] 2022-07-09 16:33
1) You are raising the Z even if Z isn't already low.  If the extruder is already near the top of the printer, you still try to raising it 4-5cm.  If you're saying that it's only supposed to raise the extruder that much only when "Z is low", then there is a bug.

2) My printer is stored inside an enclosure, and trying to load filament when the extruder is that high is difficult.

**Comment by wavexx** [comment] 2022-07-09 16:53
Makes sense. We can definitely improve this to raise only a minimal height, unless below a minimum amount (say Z<5cm). I though this was already the case, but it looks like not all conditions are covered in the same way.

**Comment by timur-tabi** [comment] 2022-12-13 05:53
Any chance that this bug will be fixed soon?  I was hoping to see a fix in 3.12

**Comment by gudnimg** [comment] 2022-12-20 17:35
In 3.13 there is now an option to use the Z parameter with M702. For example M702 Z10 will raise the extruder by 10mm. Any Z-lift done by M702 is also reverted when the unload is finished. 

This won’t make it into 3.12, there are simply too many changes.

**Comment by timur-tabi** [comment] 2022-12-22 04:56
How will that work with the control panel on the printer itself?

**Comment by Prusa-Support** [comment] 2023-01-10 17:05
Thanks for your interest.
I guess that once the the code `M702` is enabled, it can be dynamically implemented via _custom g-code (start, end, color change, pause print...)_ in Prusa Slicer.

Michele Moramarco
Prusa Research

**Comment by timur-tabi** [comment] 2023-01-10 17:42
Why would I use the slicer to unload filament?  I need this feature in the control panel of the printer itself.

**Comment by thatdecade** [comment] 2023-01-10 18:12
I too see this issue on 3.11.0-4955 on a mk3s+.  Works as @wavexx describes, the z-axis doesn't move during unload when z position is >5cm, unless I power down my machine between jobs.

To duplicate the issue, I can print any object taller than 5cm. Then power cycle the machine and select unload from control panel.  The z-axis raises regardless of current height.

To keep this feature as-is, the following should be considered:

- Machine thinks z position = 0 on power up.
- If the previous print ended within 5cm of the top, the head will crash during unload (probably ok).
- If the printer is in an enclosure, a previous z position higher than 10cm is hard to reach with your hand.
- Live z adjust can't go negative when not printing, so the head cannot be lowered before unloading filament. 
- Live z adjust is disabled during unload, holding the button is ignored.

I played around with this a bunch.  When z position is above 160mm, there is no way to prevent a crash after a power cycle and before unloading filament.  In fact, crashing the head into the top is the only way to bring it back down. Crashing the head into the top sets z position = 210mm. Allowing the user to bring the head down, and the unload raising distance feature to work as intended.

### Workaround for "After printing and removal of tall object, you want to power down.  Intending to change filaments for your next job"
**Before power down:** 
1. Hold button, then lower the z position to ~50mm.

**After Power cycle**: 
1. Crash head into top by either:
> - Hold button, then raise the z position until it crashes.
> - Select Unload Filament from menu, wait for crash, then cancel.
2. Hold button, then lower the z position to ~50mm.

**Comment by Prusa-Support** [comment] 2023-01-11 15:20
> Why would I use the slicer to unload filament? I need this feature in the control panel of the printer itself.

@timur-tabi Not sure if it will be available for direct control via control panel in the future, but as soon as the option is enabled, the parameter could be dynamically modified by the gcode print file during the print.
The parameter could be changed via custom gcode in Prusa Slicer according to the specific print scenario and the individual needs. To my understanding, the updated Z-offset value would remain stored in the printer's memory after processing the gcode string, and, starting from that moment, it would apply when you call a pause via command panel too.
Alternatively, you can modify this value via serial connection (e.g. through Pronterface).
In any case, we should wait for the option to be released for more details.
.

@thatdecade I think the same parameter would be used during the recovery from Power Panic - not sure.
About specific Power Panic issues though, you may find already opened issues like https://github.com/prusa3d/Prusa-Firmware/issues/2249, and take part in the existing discussion.

Michele Moramarco
Prusa Research

**Comment by timur-tabi** [comment] 2023-03-30 01:21
So you're saying that I could issue the M702 command every time the printer is turned on, and then the firmware will use that value whenever I unload from the control panel?

I don't want the firmware to raise the nozzle at all when unloading the printer.  But if I send "M702 0", won't that just immediately unload the filament?

**Comment by Prusa-Support** [comment] 2023-04-21 17:48
Not necessarily - that's not what I meant.
The parameter could be dynamically modified via custom g-code (start, end, color change, pause print...) in Prusa Slicer but that was just an idea.

Most importantly, the Z parameter for M702 is not implemented yet (possibly in future 3.13 firmware version).
Please wait for it to be implemented. Until then, I'm afraid all we can do is guesswork.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment] 2023-08-19 15:48
With the latest release 3.13.0, the firmware now supports additional parameters for `M701`/`M702` codes:
- Z [Z move]
- L [extrusion length]
- T [extruder number] (to be used in combination on multi-extruder printers)
- P [mmu slot index] (to be used in combination on multi-extruder printers)
- S [save filament name] (for internal purposes)
- W [preheat value] (for internal purposes)

The parameter `Z` can be used to define a custom relative Z parking position.

This should enable the firmware to set a parametric "raise Z" value which may vary dynamically (I'm not aware of currently used parameters in FW 3.13.0).
The `Z` can't be defined via LCD panel but allows custom applications (via [insert custom g-code](https://help.prusa3d.com/article/insert-pause-or-custom-g-code-at-layer_120490), [code substitutions](https://help.prusa3d.com/article/g-code-substitutions_301694), serial line...)

Michele Moramarco
Prusa Research

**Comment by timur-tabi** [comment] 2023-08-19 16:54
Is there any way to change the default Z value, so that unloading via the control panel automatically uses the new default?  I'm guessing the answer is no.  

For example, if I do "M702 Z0" from Octoprint, and then next time choose "Unload" from the control panel, will the firmware remember the Z value from the last time M702 was executed?

Also, should I open another bug to get the control panel to use the Z option, or should we keep this bug open instead?

Finally, what are the current default values for L and Z?

**Comment by Prusa-Support** [comment] 2023-08-22 16:53
Unfortunately not, it is not possible to alter the default values without building a custom firmware version, but the current implementation will open up new possibilities for future development.
For now, advanced users can send custom codes via serial line (e.g. via Octoprint) or use any of the options mentioned above to set custom codes in the print file already planned beforehand (e.g. at a certain layer height).

The default Z movement should be 50 mm
The default loading distance should be 95 mm.
The default unloading distance should be 80 mm.

When the Z and L parameters are not specified, the firmware will use the default values above.

In order to avoid confusion and for better visibility of your request, yes, I recommend closing this issue and opening a new specific one about changing these values via the printer's UI.

Please allow me to close this one already but feel free to submit further feedback below.

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2023-08-22 16:53 UTC
Labels: bug

**Comment by ttabi** [comment] 2023-08-22 17:37
https://github.com/prusa3d/Prusa-Firmware/issues/4344
