### ISSUE TITLE
[BUG]Prusa restart/Power Panic when RPI Port ON

### ISSUE THREAD

**Issue by yasars** [prusa3d/Prusa-Firmware#3802] opened 2022-12-05 18:27 UTC
with RPI PORT ON, and connected to PrusaLink
https://user-images.githubusercontent.com/41986136/205714980-ec7fa96f-3ae3-4674-99ba-d28252c06103.mp4

without RPI PORT ...only USB cable to Prusalink
https://user-images.githubusercontent.com/41986136/205715013-d40c7fbc-8386-44e2-b1b9-3deb4d277ea4.mp4

****Printer type** MK3S**
**Printer firmware version** -  3.11 and 3.12 beta and latest 3.12 RCI (i use it, but downgrade to 3.11,3.12beta to look that but same problem/error)

**Octoprint/PrusaLink**
  

****Describe the bug****
Hi if i switch my soldering iron on/off at the same socket, the prusa resets itself. but this only happens if i have the rpi port on, if i have it off and have a connection with usb, that doesn't happen. What is this? Printer reset? or Power Panic?
  
****To Reproduce****
  Switch the soldering iron on/off prusa reset itself

**Comment by gudnimg** [comment] 2022-12-05 20:32
Its possible the Raspberry Pi is restarting the printer. Does the Raspberry Pi reboot?

How is the Raspberry Pi connected to the printer? 

I think this problem is electrical in nature. Check your connections.

**Comment by yasars** [comment] 2022-12-06 01:40
Hi the raspberry os printed over rpt port the its restart ,.over usb no problem... The problem is when i will usw rpi port... I have check my.connection all fine...

**Comment by Prusa-Support** [comment] 2022-12-28 19:22
Thanks for reaching us.

Maybe the RPi port draws some power, draining power from PSU/board more quickly, and making the printer more sensitive to small power oscillations/drops.
However, I'm still not sure if the Power Panic is triggered, that would be noticeable after the reboot.
The problem though may seem related to the socket or the power strip.

Are the devices connected together on the same power strip?
Would the problem persist in the same way on a different power strip, or if connected to a different wall socket?

If the Power Panic is triggered, you will hear a beep after the reboot, and an option to recover the print will show up.
Would a Power Panic recovery message actually show up after the printer reboot? 

It could be useful to be able to reproduce the issue with other power strips or devices else than that soldering iron.

Michele Moramarco
Prusa Research

**Comment by yasars** [comment] 2022-12-28 19:52
Hi Michele , thank you ! 

i have observed the problem, i only have a soldering iron and a hot air dryer and it really only happens on this socket strip and only with the soldering iron.... it's not a power panic... i looked at the counter under > support it always stays stand at 0 and it doesn't beep either....

 thank you very much ...

**Comment by yasars** [comment] 2023-02-05 07:09
And now.after update to the  new stable ... The same error is comming  with usb too....

**Comment by Prusa-Support** [comment] 2023-02-16 15:52
We are aware that when the printer is connected via USB or RPi port, the Power Panic doesn't work at the moment. Probably that's why the Power Panic recovery is not triggered.
Maybe a Power Panic recovery will be triggered while you print on the standalone printer, via LCD panel, while RPi port is OFF and any third-party device (USB or interface pins) is disconnected.

The problem seems to be related to your specific setup though.
You can try reading the output voltage on a power strip outlet while you turn on/off the soldering iron to see if the voltage is altered.
There is a chance that it is causing interference to a portion of the mains grid, connected to the same electrical panel. You can try to read voltage on some nearby wall sockets, while someone switches the soldering iron ON/OFF.

Michele Moramarco
Prusa Research

**Comment by yasars** [comment] 2023-02-16 16:24
the prusa runs on its own power connection (circuit breaker)... i'll probably have to unscrew the soldering iron and have a look... or i'll exchange it even though it's almost new... thank you

**Comment by Prusa-Support** [comment] 2023-02-24 13:47
Maybe the soldering iron functionality is interfering with a relatively large portion of the grid.

It is still not very clear why it affects the printer only if RPi port is ON but I think it simply draws more power.
The printer may not be the only device subject to the soldering iron interferences though.

Please keep us posted if you don't mind.
We haven't got similar reports so far.

Michele Moramarco
Prusa Research

**Comment by moto52000** [comment] 2023-03-07 20:32
Hello,  I have a very similar problem.  RPi is connected to Prusa MK3S+ with the supplied USB cable running Octoprint.  Often (not every time) when I remove the build plate the PI shuts down. Other things have caused this as well (like just walking by the printer) and it seems to be static interference.  Maybe?  
I have changed the power supply and am now using the supply that comes with the PI.  
Moved the printer to another room
The only thing still on is the soft shutdown button and LED which I will remove next.  
Any ideas?

**Comment by Prusa-Support** [comment] 2023-03-28 13:46
We may be looking at a different problem.
The cause of electrical interference described in the main post is caused by other devices sharing the power grid with the printer: it is an external problem on the grid.
The reason why the problem only occurs when RPi port is enabled is not totally clear though. However, It is a fact that a device connected via USB or RPi port will draw power from the printer and may empty the printer's capacitors too fast. Also, we know that the Power Panic feature may not work correctly as a consequence.

In the last reported problem, the electrical interference may not become from the grid, but may be caused by:
a) additional third-party devices connected to the printer, not specifically designed or approved to work with the printer;
b) how the printer is connected to the grid (static charges and shocks because the printer is not correctly grounded).
Disconnecting the additional third-party devices (maybe one for a time) is surely a good troubleshooting practice to track back a connected device that may be the root cause of the problem.
Also please make sure the printer is correctly grounded. Some wall sockets or plug adapters may not ground the printer correctly or may be missing a ground channel.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment] 2023-04-20 13:16
This issue may not seem to be relevant to the firmware itself because caused by external factors.

The part of the issue that concerns the Power Panic should be already sufficiently documented in issue https://github.com/prusa3d/Prusa-Firmware/issues/3802 instead.

This issue can be closed as irrelevant for the firmware and partly duplicated.

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2023-04-20 13:16 UTC
Labels: awaiting response, electronics, third-party
