### ISSUE TITLE
High pitch noise from cooling fan at less than 100% fan speed

### ISSUE THREAD

**Issue by kacperd2808** [prusa3d/Prusa-Firmware#706] opened 2018-05-01 09:17 UTC
While printing with PET-G I need to decrease fan speed from 100% to 0-60% and the high pitch noise from cooling fan gives me a headache.

**Comment by magkopian** [comment] 2018-05-01 10:25
That's because the used PWM frequency is on the audible range. There's already an open issue regarding this #460.

**Comment by DRracer** [comment] 2020-09-21 06:42
Duplicate of #460 , closing

**Closed as completed by DRracer** 2020-09-21 06:42 UTC
