### ISSUE TITLE
[BUG] keeps ejecting filament after a filament runout

### ISSUE THREAD

**Issue by Fredlandator** [prusa3d/Prusa-Firmware#3038] opened 2021-02-20 08:34 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.
 I did, didn't found it.

**Printer type** - Mk3s+
**Printer firmware version**- 3.9.3

**MMU Upgrade** - no
**MMU upgrade firmware version N/A

**SD card or USB/Octoprint** : SD card
  
**Describe the bug**
 After a filament runout
- Printer will ask you to press the button to eject what's left in the extruder.
- after ejecting leftovers, asks if it went smooth
- after loading new filament, asks if new filament loading went smooth (this is typically when I removed extruded filament due to the process of loading)
-  when yes (happy with the way the new filament has been loaded) it extrudes more filament for no expected reason and then move to the print, with this 5cm or so filament string that will mess up the print
  
**To Reproduce**
  
just follow the steps above

**Expected behavior**
 
After pressing the button to say that yes, loading filament went thru, I don't expect printer to extrude filament again. at least, I expect to have a chance to clean the nozzle before it moves back to the print
  
**G-code**
  Not a G-code related issue. Happens on all my I3, all G-codes.

**Video**
  Let me know if a video is needed, but I don't feel like a video is necessary as it is very easy to duplicate.
In case I am wrong, let me know, and I will make one.

**Comment by 3d-gussner** [comment] 2021-02-23 17:52
The extra 5cm are `Feed a little of filament to stabilize pressure` and are `#define FILAMENTCHANGE_RECFEED 5` in the variants files.
So if you want to change it feel free to compile your custom firmware.

This behavior is on purpose otherwise there is a chance for under extrusion after the filament change.
After confirming "Yes" you can stay prepared to clean the extra filament.
1. Press Yes
2. the extruder pushes the extra amount of filament
3. Grab the filament while
4. the hotend moves to previous xy pos
5. the hotend moves to previous z pos

So you should have some time to grab the filament.

I know it is not the best answer I can give, but better a stable hotend pressure than under extrusion.
 
Please check the other issues.

Duplicate of
https://github.com/prusa3d/Prusa-Firmware/issues/197
https://github.com/prusa3d/Prusa-Firmware/issues/1999

Please consider to close this bug report as it is NOT a bug.

**Closed as completed** 2021-03-19 15:01 UTC
Labels: bug
