### ISSUE TITLE
Weird sd card error

### ISSUE THREAD

**Issue by william14235** [prusa3d/Prusa-Firmware#2196] opened 2019-09-11 22:28 UTC
When I try to print a file, it heats up but then doesn't start the print and I need to go to print from SD card again to start the print

**Comment by cdburgess** [comment] 2019-09-21 22:22
I have experienced this as well. I found this typically happens when I replace the SD Card without a reset. Once I reset the machine it will work just fine.

**Comment by leptun** [comment] 2019-10-06 19:45
A fix has been merged into 3.8.1-RC1. Please check if the problem is solved and close the issue if it is so.

**Closed as completed** 2019-10-08 23:28 UTC

**Comment by cdburgess** [comment] 2019-10-09 01:18
Sadly, I don't have access to Windows or Linux. I use Mac. I tried following the instructions for the build process, but it appears there are missing pre-requisites.
