### ISSUE TITLE
MMU2 fails to load filament under FW 3.7.0

### ISSUE THREAD

**Issue by Gountled** [prusa3d/Prusa-Firmware#1700] opened 2019-04-05 15:48 UTC
I have the strange behavior, that it does all the heating, mesh bed leveling and after that it tries to load the filament. All is fine and filament is loaded into the nozzle, but afterwards it is unloaded completely again. After a couple of time doing this, the printer tries to print from back to front instead the "normal" direction, but without any filament and the heater is also switched of.
I switched the IR sensor in the menu on and off, no change.
I switched the MMU to normal and to stealth mode, no change.
I can see, that the IR sensor reacts when the filament reaches the nozzle, but still it is retracted immediately after.

Switching back to 3.6.0 solves this problem immediately!

**Comment by leptun** [comment] 2019-04-05 15:51
Duplicate of #1689

**Comment by jindrichbenes** [comment] 2019-04-08 11:12
Have you upgraded fw of MMU unit itself?

**Comment by PavelSindler** [comment] 2019-04-08 12:01
Are you printing from SD card or is it USB print (Octoprint, Pronterface...)?

**Comment by Gountled** [comment] 2019-04-08 13:51
Usually I am printing via Octoprint.
Both have been Upgraded, printer firmware and also MMU2S

**Comment by fnordsh** [comment] 2019-04-14 20:14
I had the same issue. I thought my IR sensor was calibrated well, but shifting it a tiny bit to the right solved the issue for me.

**Comment by Gountled** [comment] 2019-04-15 15:35
I will give it a try, but firmware 3.6 works like a charm.

**Comment by fnordsh** [comment] 2019-04-15 16:14
I think 3.7 uses the IR sensor more extensively, which is probably a good thing (once it's calibrated right).

**Comment by Gountled** [comment] 2019-04-16 09:19
So I flashed 3.7.0 today aigain and moved the IR sensor as much to the right as it was possible.
The result is: It loaded the filament as it should! Thanks for the advice!

Printing single colour calibration cube right now (from SD Card). Next test will be a dual colour print.

**Comment by fnordsh** [comment] 2019-04-16 09:23
Nice! Glad I could help!

**Closed as completed** 2019-04-18 09:01 UTC
Labels: FW 3.7.0, MMU2S
