### ISSUE TITLE
Initial extrusion

### ISSUE THREAD

**Issue by mkh595** [prusa3d/Prusa-Firmware#2276] opened 2019-10-16 09:56 UTC
MK3S: 3.8.0-2684
MMU2: 1.0.6-372

When print starts, nozzle moves to left front corner and extrude without move for 12 seconds. This create blob which size depends if filament was already in the nozzle or just moved from MMU2.

![20191015_155226_2](https://user-images.githubusercontent.com/30566575/66907219-4be23a80-f009-11e9-8d98-f4e40820efbe.jpg)

Then moves right and back to the start position, nozzle catch this blob

![20191015_155236_2](https://user-images.githubusercontent.com/30566575/66907248-58ff2980-f009-11e9-9cd4-ced2faff64ef.jpg)

and drop it somewhere in the print area. 

![20191015_155246_2](https://user-images.githubusercontent.com/30566575/66907493-b4311c00-f009-11e9-9a24-d785fdf83288.jpg)

Another example

![20191015_180535_2](https://user-images.githubusercontent.com/30566575/66907680-05d9a680-f00a-11e9-89cf-97c318675e18.jpg)
![20191015_180621_2](https://user-images.githubusercontent.com/30566575/66907691-096d2d80-f00a-11e9-8aab-228e882c9c88.jpg)

If I remember well, before upgrade to MMU2 there was initial extrusion shorter always with move without return back. 
Is there reason why nozzle is not moving? If has to create such blob, can be the move back shorter (e.g. 10mm less) to not hit this blob?
Issue is mostly on Powder coated sheet because adhesion is not so good like on smooth PEI.

**Comment by vintagepc** [comment] 2019-10-31 18:04
This sounds like a duplicate of #2069 

Note you can get this if your sensors (IR/FINDA) are not calibrated correctly, if the IR continues to report zero, the MMU will force-feed your extruder and make a blob until the IR sensor happens to trip.

**Comment by mkh595** [comment] 2019-11-13 19:54
It is not issue of IR sensor, I have LED indicator, IR sensor works corectly.

![image](https://user-images.githubusercontent.com/30566575/68798853-769acf80-0657-11ea-9f39-8d8899abe653.png)

**Comment by leptun** [comment] 2019-11-13 20:03
@mkh595 is this a single color MMU print?

**Comment by mkh595** [comment] 2019-11-15 12:48
yes, single color MMU. 

Purge line is created by 'Beginning Gcode' in PrusaSlicer delivered in '...MK3S MMU2S single' profile. I modified it to return 10mm less to not hit blob.
Size of blob depends if filament was unloaded from previous print or was already in nozzle, e.g. when previous print was cancelled by panic button.

```
; purge line
G1 X55.0 F2000.0
G1 Z0.3 F1000.0
G92 E0.0
G1 X240.0 E25.0 F2200.0
G1 Y-2.0 F1000.0
G1 X55.0 E25 F1400.0
G1 Z0.20 F1000.0
;G1 X5.0 E4.0 F1000.0    <= Do not return to start position
G1 X15.0 E4.0 F1000.0 
```

**Comment by JohnnyDeer** [comment] 2021-02-03 08:25
Duplicate of #2069, I´m closing.

**Closed as completed by JohnnyDeer** 2021-02-03 08:25 UTC
