### ISSUE TITLE
thermal anomaly

### ISSUE THREAD

**Issue by MG-BFL** [prusa3d/Prusa-Firmware#4016] opened 2023-02-12 23:02 UTC
### Description of the bug

my mk3s said to install new firmware.  I downloaded and installed.  my printer said I need to run calibration....
system shuts down after a lot of testing/calibration and displays ... thermal anomaly.

Printer will not continue ....  I can not run a file to print.

Has worked fine for years ......

### Project file & How to reproduce

no file will run

### Checklist of files included above

- [ ] Project file
- [ ] Screenshot

### Version of PrusaSlicer

2.5

### Operating system

win 10

### Printer model

mk3s  (kit)

**Comment by neophyl** [comment] 2023-02-13 07:19
This is an issue for the printer firmware and not Prusa Slicer.  The Mk3 github is located here https://github.com/prusa3d/Prusa-Firmware/issues
There are several open and existing issues for thermal anomaly caused by the new 3.12 firmware.  Please go and read them.

**Comment by MG-BFL** [comment] 2023-02-13 15:30
what do I do to continue?  Can I use an older version of the firmware and instll it?

**Comment by knightsljx** [comment] 2023-02-14 17:05
flash back to 3.11 until they fix this 'feature'

**Comment by MG-BFL** [comment] 2023-02-14 19:06
thank you
Rich Johnson
Los Banos, Ca.
Maker

www.Rjgardenrailroad.com
***@***.***

**Comment by sarusani** [comment] 2023-02-15 14:15
If your printer is 100% original with no modifications you should contact support and figure out what's wrong with your printer! 

If you have non stock parts on your printer going back to a older firmware is an option, or you can disable the thermal model by sending G-code M310 S0 followed by M500 to make it permanent.

**Comment by Prusa-Support** [comment] 2023-03-24 13:32
Thanks for reaching us.

That's right, in case you use genuine stock Prusa parts, reaching out to the official Support for help could be a good idea.
https://help.prusa3d.com/article/customer-support_2287

Generally speaking, **(1) a careful hotend assembly checkup** + **(2) PID tuning** + **(3a) new calibration** (preferably first **(3b) lower the printhead on the bed** for a more resilient calibration) may solve the problem and can improve the _Termal Model_ accuracy.

Modded printers or printers using third-party components in general, may require tweaking for the _Thermal Model_ to work correctly.
**Please find more about the thermal model functionality and parameters in the relevant Pull Request https://github.com/prusa3d/Prusa-Firmware/pull/3552#issue-1324629390.**
Also please consider creating a log file as explained at https://github.com/prusa3d/Prusa-Firmware/issues/3636#issuecomment-1262926997 to be uploaded in the thread or a relevant issue: please check the existing issues under https://github.com/prusa3d/Prusa-Firmware/labels/thermal%20model label. It may be of use for our developers to understand the specific problem or for further future improvements.
 Of course, in the case of non-stock parts, please provide precise information about your printer's hardware too.
Meantime, you can disable the thermal calibration by running two simple codes (`M310 S0` followed by `M500`) via Pronterface or similar programs, and "normally" use the printer without the thermal model if necessary.

This issue will be closed as a duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/3908.

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2023-03-24 13:32 UTC
Labels: thermal model
