### ISSUE TITLE
When continue from pause the heating of filament failed

### ISSUE THREAD

**Issue by loketak** [prusa3d/Prusa-Firmware#470] opened 2018-02-08 22:01 UTC
FW 3.1.1 b150 RC5
When I choose continue (Pokracovat) after I paused printing (Pozastavit tisk) the printer "stars heating" the extruder but in fact the current  temperature still fall down and set point temperature was set to 0. When I again in menu choose pause printing and try to heat it up from menu, the extruder correctly heats up. However after the extruder reach set point (for PLA 215 C) the set point was changet to 0. 
![image20180208_224925406](https://user-images.githubusercontent.com/18590662/36000663-eac34376-0d23-11e8-8698-3636938d814c.jpg)

**Comment by misan** [comment] 2018-02-11 11:38
I reckon it is a duplicate of #221

**Comment by GitHubMarine** [comment] 2018-02-27 02:56
I'm having the same issue.  The nozzle fails to heat up and decreases in temperature instead of increasing after I selected "Resume" from a pause.

**Comment by Prusa-Support** [comment] 2022-05-05 13:55
Duplicate of  [#221](https://github.com/prusa3d/Prusa-Firmware/issues/221)

Marina Curzi
Prusa Research

**Closed as completed by Prusa-Support** 2022-05-05 13:55 UTC
