### ISSUE TITLE
Firmware crash AGAIN

### ISSUE THREAD

**Issue by Cmos2112** [prusa3d/Prusa-Firmware#4109] opened 2023-03-24 23:55 UTC
### Description of the bug

I had a perfectly functional MK3S+ with MMU2 working just fine but asking me to upgrade the firmware every time I started a new print. So I updated both the printer and the MMU. I expected it to work. I have fought every single thing on this printer since the upgrade to the new firmware. I have reset the mmu to zero and recalibrated the bowden tube for all 5 filaments as per instructions. I have shut down the thermal whosawhatsit because it is not compatible with E3D Revo. I have been really patient all the while and now I want to burn this sob down to the ground and buy an X1C to save myself the royal pain in the posterior. I have not made huge dramatic changes to this printer, and in fact the changes I had made were working great on the old firmware.  So the addition of the Revo and the change to a gear reduction extruder aside this is otherwise stock. so why does the mmu not feed a filament to the extruder during a print now?
I had to change some things in the print profile to make the slicer recognize my filament profiles and then sneak a .8 nozzle size in place of the .6 stock profile for the mmu setup. So maybe that is where the issue resides. But why would a functioning profile not turn the motor to load filament to the extruder. I am certain I did not turn off the feed motor for the mmu with any setting in the slicer. The selector moves successfully to the filament I want to use, but it will not feed it out. The printer says the firmware crashed and to contact help for support but i ended up here because I am too dumb to ask the right question in the right format at the right time. 
I don't know how to get the debug file off the printer and I don't know why I ended up here and not somewhere that can help me. So read this rant and delete it if you must and I will go on trying in vain to repair what NEVER SHOULD HAVE BROKEN IN THE FIRST PLACE!
PS if you made it through my obvious frustration and haven't written me off as a lunatic already, please offer your suggestions and advice. If I find some way to ever get back to this report and see what you had to tell me it will be a miracle, but I do appreciate the effort on your part random human.

### Project file & How to reproduce

I have no idea how to do this at all.
I am not a programmer I just want the thing to do the thing it's supposed to do like it did without incident 2 weeks ago.
Also I am sorry that I don't seem very helpful in trying to get this resolved. I am mad enough to light my hair on fire right now. I should not be on the internet ranting but I am anyway.
Please don't block me forever, just laugh at the dumb guy and move on or offer help.

### Checklist of files included above

- [ ] Project file
- [ ] Screenshot

### Version of PrusaSlicer

2.5.1

### Operating system

windows 11

### Printer model

MK3S+

**Comment by neophyl** [comment] 2023-03-25 08:30
You want the Mk3 github- https://github.com/prusa3d/Prusa-Firmware/issues  this is the prusa slicer github project.

The best advice to those having issues with the 3.12.x firmware is to roll back to the previous versions.

**Comment by Cmos2112** [comment] 2023-03-25 14:25
Neophyl, thanks for that. I did realize that as I was finishing my rant. I was just so ticked off I couldn't think straight at the moment. Caffeine imbalance or mental imbalance or whatever. 
Time to make like 90's walmart and do a Rollback.

**Comment by neophyl** [comment] 2023-03-25 14:39
You can turn the nag off though, if you look in the start gcode field in Prusa Slicer>Printer Settings.>Custom Gcode youi should see a line like the following -
M115 U3.12.2 ; tell printer latest fw version, 
just comment out that line and save it as a custom printer profile.  Then when you slice with that 'new' printer it wont do the firmware compare.

**Comment by bdoogan** [comment] 2023-03-25 18:28
I am having the exact same issue!! Mk3s with mmu2s, was working flawless ( for the most part) and kept getting the annoying ,message so I figured I would update, now i am getting  TM error message ( fyi- i am running the revo6). I started going through the calibration process and then it errors out on the TM setup. SO frustrating!! This should have been working out prior to being released.

**Comment by Cmos2112** [comment] 2023-03-25 19:26
The TM (thermal model)is known to be incompatible with Revo6. But there is
a fix for that. A simple 2 lines of g-code. Write it in notepad or send it
through Pronterface.

**Comment by bdoogan** [comment] 2023-03-25 20:41
Hi, thanks for the info. Can you let me know where to find that info?

**Comment by Cmos2112** [comment] 2023-03-25 21:29
I can check on Monday at work where the Prusa is. But I'm pretty sure I
found it by searching the exact error that it spit out. And I found the
right code pretty fast.

I may not be as completely useless as I felt in the op but if you never
made a text g-code file it is so simple even I can do it.
In notepad or similar low tech text editor type your g-code, for example

M92 E724 ; Set extruder E-steps
M500 ; Save changes to eeprom

Then click "save as" and select the file type as "all files" or "any file".
Whichever option it gives you. And name this text file something you will
recognize.
For example "Set_esteps.g-code"
If you did it right you can save it to an SD card right from notepad, then
put it in your printer and select "print from sd"
Which is really just a generic label for "run program".
This is a great and easy way to make adjustments to your printer.
Alternatively, you can connect to your printer directly from your pc with
Pronterface and type the code directly into the text box at the bottom
right.
You don't need any comments if you do it this way but they don't hurt
either. Comments in any code are just notes to help humans figure out what
the code is doing.

Maybe you already know all that but maybe someone else will read through my
response and a keystone will fall in place on their mental bridge.

**Comment by Prusa-Support** [comment] 2023-05-05 19:49
Thanks for your message and I'm sorry for the whole situation.

While you can count on our full support in the official [Customer Support](https://help.prusa3d.com/article/customer-support_2287) channels, and freely carry discussions in our [official Forum](https://forum.prusa3d.com/), GitHub is the place where we keep track of bugs and feature requests along with the community.

We appreciate you sharing your personal experience but this issue is quite generic or simply puzzling due to several undefined possible concerns about your printer. As a consequence, this issue could be closed as invalid.
A proper troubleshooting session with our Customer Support can remove a few doubts and clarify the nature of the problem/s.

On a side note, calibrating the filament loading distance may only make sense if you use a custom-length tube on the MMU2S, or if you are running on an obsolete MMU2 model. Interestingly enough, virtually all MMU2 have possibly been upgraded to MMU2S for free (more in [blog post](https://blog.prusa3d.com/original-prusa-i3-mk3s-and-mmu2s-release-sl1-and-powder-coated-sheets-update_29599/)). Not sure if this is an exception.

In case of concerns about the Thermal Model protection, please check the already existing issues. These are supposedly being labelled with a [thermal model](https://github.com/prusa3d/Prusa-Firmware/issues?q=is%3Aissue+is%3Aopen+label%3A%22thermal+model%22) tag. If you are a Revo user, due to its popularity, we are collecting data in issue https://github.com/prusa3d/Prusa-Firmware/issues/4105 (pinned).

I seemed to notice an increase in Firmware Crash cases, possibly relate to FW 3.12.x and the MMU - _no bug confirmed_ (yet).
Step 1) Downgrade and upgrade the firmware a few times to make sure the problem is only reproducible with FW 3.12.x.
Step 2) Try a "combined" and complete factory reset ([Einsy ](https://help.prusa3d.com/article/factory-reset-mk2s-mk2-5s-mk3s_2216)+ [MM-controller](https://help.prusa3d.com/article/factory-reset-mmu2s_1920)).
Step 3) Monitor the specific issues https://github.com/prusa3d/Prusa-Firmware/issues/4110 (possibly duplicated by https://github.com/prusa3d/Prusa-Firmware/issues/4155, https://github.com/prusa3d/Prusa-Firmware/issues/4186) as likely closely related.

Would you mind closing this issue?

Michele Moramarco
Prusa Research

**Comment by Cmos2112** [comment] 2023-05-05 20:05
Yes sir,
You may close this issue.
Long story short. I saw new firmware updates that took the thermal model
into consideration. Refreshed both boards, pid tuned, calibrated everything
once more, and still had an issue, however, I believe I have it solved now.

With the addition of an led to my filament sensor at the tool head, I found
I was getting multiple false positives for filament in the extruder. Once I
remedied that situation there seem to be no more troubles so far.

Thank you and thank everyone at Prusa for the fantastic support.
I love you all.(in the kindest most non-threatening way possible. )

Have a wonderful weekend.

**Comment by Prusa-Support** [comment] 2023-05-06 16:53
Thank _you_ for supporting our company and the Open Source.

Thank you for your kind update too.

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2023-05-06 16:53 UTC
Labels: duplicate, invalid, awaiting response
