### ISSUE TITLE
[Suggestion] Nozzle change quick button

### ISSUE THREAD

**Issue by cyxlops** [prusa3d/Prusa-Firmware#1750] opened 2019-04-18 16:04 UTC
It would be really nice to have a quick shortcut button in main menu to initiate a nozzle change. Where nozzle temp is set to 285 instantly without the need to dig deeper into settings and rotate the knob multiple times. It just improves efficiency this way.

**Comment by crua9** [comment] 2019-04-22 20:47
It would also be interesting if they added within that a guide on what to do step by step. I mean you have the lcd panel, and it can tell the user what to do.

**Comment by gudnimg** [comment] 2023-07-24 17:47
Duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/1579 we've now implemented "Nozzle Change" menu into the firmware.

**Closed as completed by gudnimg** 2023-07-24 17:47 UTC
Labels: enhancement
