### ISSUE TITLE
Issue: V3.1.0-RC1 slow menus and glitches

### ISSUE THREAD

**Issue by jjisnow** [prusa3d/Prusa-Firmware#226] opened 2017-10-05 21:01 UTC
Hi, I've noticed a few issues after printing the 1st layer calibration with the pre-release new firmware:

1. 'Pr' in 'Prusa' flashes on and off slowly
2. The menus suddenly slow down dramatically
3. Button presses now shriek instead of give a small click sound - 

The last 2 I believe imply some kind of lagging processing going on.

**Comment by 3d-gussner** [comment] 2017-10-06 13:26
Have same issue with the LCD, during the Wizzard the 1st two letters some dots of 'Bed Heating......' message fade off and on slowly.
Also during the Wizzard it switches for a moment to Info screen and then back to the Wizzard between different commands. The Wizzard calibration also runs very very slow sometimes the nozzle stops for a moment.

**Comment by michalzielanski** [comment] 2017-10-06 20:43
I have the same. Even if the printer does not print anything.

**Comment by PavelSindler** [comment] 2017-10-06 22:26
That is interesting. Thank you for reporting this.

**Comment by WarpZoneNL** [comment] 2017-10-07 13:08
MK2S

- While running setup after factory reset;
     - 4 point calibration; it waits a few minutes after calibrate the 4th point!
     - 9 point Z-calibration; it waits a few minutes after calibrate the 9th point!
     - After V2 (3!) calibration code, it ask to redo... Text one jumps to fast and then you see, "Headbed?" Place an extra line like "Redo calibration?" >yes > no

- Normal Modus
     - After pressing LCD button, it beeps, and rebuild the LCD very very slowly
     - LCD, last line, first two digets are flashing sometimes
     - LCD is really really slow building up tekst
     - LCD is sometimes giving rare symbols.... Hotent temp: 214/ $
     >> After power OFF -> Onn the LCD is fast!

**Comment by cristiansavaro** [comment] 2017-10-12 07:37
These issues were introduced somewhere between 3.0.12 (no issues) and 3.0.12-7 (lcd menu issues present). I've tested both myself !

**Comment by PavelSindler** [comment] 2017-10-13 15:06
Did this issue appeared right after turning on the printer, @jjisnow ? Or was it really triggered by running first layer calibration?

**Comment by PavelSindler** [comment] 2017-10-13 16:12
It seems that it is caused by commit https://github.com/prusa3d/Prusa-Firmware/commit/7d2d6c6fdcb296e776c7143cc72f6ca2271aa11 .

**Comment by jjisnow** [comment] 2017-10-13 21:50
@PavelSindler, I only noticed it after printing a first layer calibration, but it may very well have been there from the start.

**Comment by cristiansavaro** [comment] 2017-10-14 05:04
@PavelSindler , it appears random when getting to the menu, but rarely for me at least. Once it appears only reset will resolve it. I hope all the hints can help you in pinpointing the issue and solve it.

**Comment by PavelSindler** [comment] 2017-10-17 09:21
It has been fixed by PR https://github.com/prusa3d/Prusa-Firmware/pull/241.

**Closed as completed by PavelSindler** 2017-10-17 09:21 UTC
