### ISSUE TITLE
[BUG] filament autoloading stopped and not finished when SD card inserted

### ISSUE THREAD

**Issue by stepheneb** [prusa3d/Prusa-Firmware#3128] opened 2021-04-26 14:53 UTC
- Original Prusa i3 MK3S kit
- firmware: 3.10.0-RC2

I started to autoload filament and halfway through the procedure I inserted an SD card. The system displayed message about sorting files and the ongoing autoload procedure was terminated before any filament had been extruded.

**Comment by stepheneb** [comment] 2021-04-26 14:57
Perhaps a related issue: #2651

**Comment by JohnnyDeer** [comment] 2021-04-27 13:28
Hi @stepheneb, I'm unable to reproduce this issue. Printer behave as expected, load filament and show dialog about successful load even if i stay in SD menu. If i choose file to print during load printer does reset.
Can you please uplad video with this issue? Thank you

**Comment by awenelo** [comment] 2021-04-27 17:46
@JohnnyDeer, I can cause something similar to this issue on 3.10.0-RC1, but the only thing that happens is that the `Loading filament` message disappears, the autoload still brings up the `Is filament extruding and with the right color?` menu and continues to run the extruder as expected.

Expected message during autoload:
![IMG_20210427_131804190](https://user-images.githubusercontent.com/56133692/116287524-85e3df00-a75e-11eb-8403-fb2a1086b77b.jpg)

Actual message during autoload after SD is inserted:
![IMG_20210427_131817539](https://user-images.githubusercontent.com/56133692/116287568-91cfa100-a75e-11eb-94da-cc86f4504c24.jpg)

**Comment by stepheneb** [comment] 2021-04-30 22:09
@JohnnyDeer, I tried reproducing today and wasn't able to. The printer stays on 24x7 and is printing almost all that time. I pressed the reset button today before I tried to replicate.

I will try a few more times.

**Comment by JohnnyDeer** [comment] 2021-07-19 06:46
@stepheneb did you reproduce this issue since? If no could we close it as "unable to reproduce"?

**Comment by JohnnyDeer** [comment] 2021-08-19 08:10
I'm closing this issue because there are no responses.

**Closed as completed by JohnnyDeer** 2021-08-19 08:10 UTC
Labels: bug, awaiting response
