### ISSUE TITLE
  [ENHANCEMENT]Main menu is shifted

### ISSUE THREAD

**Issue by espr14** [prusa3d/Prusa-Firmware#2620] opened 2020-04-18 15:10 UTC
i3 MK3S FW 3.9.0 RC1

Go to menu "Support" and click on "Date:". It will return you to the main menu but the "Support" line is not at the bottom even it is the last item in the list.

**Comment by leptun** [comment] 2020-04-18 17:46
The issue is that the "view" is not saved when switching menus, just the selected item. As a result, the view is kept from the previous screen. The support menu is the only one which has a "back" item so low in the menu. All other menus have the "back" button at the top. We could do a check, where when changing menus, the view is adjusted automatically to the limit.

**Comment by MohanMaker** [comment] 2020-09-07 15:46
Same issue here with firmware version 3.9.0 - 3421 on MK3S. Do you have a fix @leptun? Maybe it could be implemented into 3.9.1?

**Comment by leptun** [comment] 2020-09-07 16:47
@MohanMaker Thank you for reminding me of this issue. I just wrote a quick patch that should fix the issue described by OP. Not sure if there is enough time for it to be merged into the 3.9.1 final release, but in 3.10 for sure. 
If you want to give the patch a try, the PR with the fix is #2828

**Comment by MohanMaker** [comment] 2020-09-07 19:30
Great, will give it a try. Excited that it will be in 3.10!

**Closed as completed** 2020-09-08 07:45 UTC
Labels: enhancement
