### ISSUE TITLE
Preheat nozzle change

### ISSUE THREAD

**Issue by Colonelsander11** [prusa3d/Prusa-Firmware#3406] opened 2022-02-15 00:26 UTC
Would like to see in the preheat menu, a nozzle change option instead of going settings>temperature>nozzle>crank to 270 instead press>preheat>nozzle change

**Comment by Prusa-Support** [comment] 2022-07-19 15:53
This will be closed as a duplicate of issue #2972.

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2022-07-19 15:53 UTC
Labels: feature request, HW issue, temperature, materials
