### ISSUE TITLE
Unwanted feeding after mid-print filament change

### ISSUE THREAD

**Issue by nickrbogdanov** [prusa3d/Prusa-Firmware#3546] opened 2022-07-21 17:39 UTC
**Printer type** - MK3S
**Printer firmware version** -  prusa3d_fw_MK3S_MK3S+_3_11_0_4955.hex

**MMU upgrade** - no
**MMU upgrade firmware version** - no

**SD card or USB/Octoprint** - USB/Octoprint

**Describe the bug**

When my filament runs out during a print:

1. Prusa starts beeping at me asking me to unload
2. I push the button to unload
3. Prusa asks if the filament was unloaded correctly
4. Push the button to acknowledge
5. Prusa asks me to feed new filament and I do so
6. Prusa feeds the filament a bit
7. Prusa prompts me to ask if the color is correct
8. I remove the "scrap" filament from the nozzle and then hit Yes
9. Prusa then feeds about another 5cm of filament without prompting
10. Prusa immediately moves the print head back to the object and continues printing

Step 9 is the problem.  This extra 5cm of scrap filament gets dragged along with the nozzle and sometimes gets deposited onto the project.  I have to quickly grab my pliers and "chase" the moving print head to remove it.

This happens after I run out of filament and need to replace the spool.  It also happens after an M600 color change.  I looked at the gcode and saw that there's nothing in there asking the Prusa to feed 5cm of extra filament after the M600, so I'm guessing this is something the the firmware is doing on its own.

I am using the latest PrusaSlicer.
  
**To Reproduce**

Run out of filament, or manually enter an M600 color change.
  
**Expected behavior**

Don't feed an extra 5cm of filament after the user acknowledges that the new filament is feeding correctly.
  
**G-code**

n/a

**Video**

I can take a video later if the description isn't clear

**Comment by neophyl** [comment] 2022-07-25 06:35
Duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/2502  or even https://github.com/prusa3d/Prusa-Firmware/issues/197

**Comment by Prusa-Support** [comment] 2022-07-27 13:45
Hello! Thank you @nickrbogdanov for the report, and @neophyl for pointing to the duplicate threads. We are aware of this, we are looking into possible solutions to improve this aspect but sadly no timeframes yet. I'll close this specific thread as duplicate. 

Alessandro Pantaleo
Prusa Research

**Closed as completed by Prusa-Support** 2022-07-27 13:45 UTC
Labels: bug
