### ISSUE TITLE
[BUG] Minor display issue (wrong material) after filament runout

### ISSUE THREAD

**Issue by imnotme** [prusa3d/Prusa-Firmware#3165] opened 2021-05-26 15:16 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

Searched using different keyword and even on closed issue, all seems linked to the IR sensor of the i3

Also, I know this is a minor issue.

**Printer type** - Mini+
**Printer firmware version**-  4.3.1

**SD card or USB/Octoprint**
  USB Key provided

**Describe the bug**

0. PETG Print, PETG settings (240/90), Sliced with Prusa 2.3.1
1. Filament runout
2. Parking, filament ejection
3. New filament introduced (Still PETG)
4. Screen is waiting to confirm it can load the filament, not asking which material
5. Filament loaded, print resumed
6. In the bottom right of the screen, now it's not "PETG" but "PLA" displayed
7. Temperature are not changed :240/90 (However, I have not checked, but PETG still extrude properly)  -> Only a display issue

  
**To Reproduce**
 See bug description
  
**Expected behavior**
Ask which material is now loaded, or just assume it's the same as the previous one
  
**G-code**
Can provide sliced file if necessary

**Comment by JohnnyDeer** [comment] 2021-06-03 07:18
Hi @imnotme, this issue is in wrong repository and is duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1400. I´m closing this one.

**Closed as completed by JohnnyDeer** 2021-06-03 07:18 UTC
Labels: bug, invalid
