### ISSUE TITLE
After filament load, starts to extrude before returning to print 

### ISSUE THREAD

**Issue by sledjunk** [prusa3d/Prusa-Firmware#2801] opened 2020-08-12 14:01 UTC
**Printer type** - [e.g. MK3S,
**Printer firmware version**-  3.90 - 3421

**MMU Upgrade** - none

**SD card or USB/Octoprint** USB Pronterface

**Describe the bug**
When I print a job with a colour change, or if there is a filament runout, this error occurs.
After loading the new filament, I always clean the nozzle so that the job can start cleanly, especially with PETG.  However, when I am finished, and press the knob to let the job continue, on the way to the print surface, the extruder starts to turn, and by the time the nozzle touches down, the is a considerable blob to be deposited on the print job which often then causes crashes.   
**To Reproduce**
Simply force a filament change in the middle of a job by cutting the filament above the extruder anad wait for it to run out.  Do the filament change, optimally with a different colour, and watch what happens.  This is much easier to see if you ave some sort of indicator to see when the extruder is turning.  A simple mark on the shaft will do.

It would also be nice if the extruder could be raised higher off of the print bed during the filament change to allow easier access to the nozzle area.

**Expected behavior**
  

**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.
[19mm Wrench 2 colour_export.zip](https://github.com/prusa3d/Prusa-Firmware/files/5063411/19mm.Wrench.2.colour_export.zip)

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by 3d-gussner** [comment] 2020-08-12 16:52
Thanks for the bug report but it is a duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/2502
Please consider next time to search all (also closed) issues if your issue may have been already addressed.

BTW Your Issue report is a top example how to fill out the template! Thanks for that.

**Comment by sledjunk** [comment] 2020-08-12 21:24
Sorry about the double post.  I guess I didn't read far enough.

**Comment by JohnnyDeer** [comment] 2020-11-26 10:53
Closing as duplicate of #2502.

**Closed as completed by JohnnyDeer** 2020-11-26 10:53 UTC
Labels: bug, duplicate
