### ISSUE TITLE
3.7.2 causes loud beep on power off (duplicate)

### ISSUE THREAD

**Issue by Seikilos** [prusa3d/Prusa-Firmware#1998] opened 2019-07-14 12:13 UTC
Just upgraded to 3.7.2 on my MK3S and noticed something odd:
I usually power off the printer by using a switch on the socket (because there are other devices with the printer that are turned on and off) but after the upgrade to 3.7.2 the printer makes a very loud beep when I switch it off that way (the beep on power on is much more quiet)

I also tested powering it off via the printer's PSU power button and while the beep is shorter it is still there but seems to be cut off in the middle. Is this a new feature?

It happens also without connecting an OctoPrint Raspi to the USB socket.

**Comment by leptun** [comment] 2019-07-14 12:15
It is a bug. Duplicate of #1929

**Closed as completed** 2019-07-14 12:17 UTC
