### ISSUE TITLE
High pitched sound from extruder fan on Mk3

### ISSUE THREAD

**Issue by fjn777** [prusa3d/Prusa-Firmware#1238] opened 2018-10-07 16:55 UTC
Just got my Mk3 and noticed that there is a very high pitched sound from extruder fan when printing petg for example. What can be done about this????

**Comment by hoppke** [comment] 2018-10-07 17:05
Another happy MK3 user :) It's doing this by design, see Issue #460

**Comment by Prusa-Support** [comment] 2022-05-10 13:11
Hello! I apologize for the late response to this issue. The issue was indeed related with #460, I am closing this issue as this aspect has been addressed in the meantime on a previous FW release. 

Alessandro Pantaleo
Prusa Research

**Closed as completed by Prusa-Support** 2022-05-10 13:11 UTC
