### ISSUE TITLE
  [ENHANCEMENT] FINDA and IR sensor status on "MMU load error"

### ISSUE THREAD

**Issue by morimorida** [prusa3d/Prusa-Firmware#2873] opened 2020-10-26 18:16 UTC
Can we have a more helpful information along side with MMU load error and providing us with sensor status during the loading/unloading error?

Like

MMU failed to load...
IR = 1 , FINDA = 1

**Comment by vintagepc** [comment] 2020-11-02 15:09
this is a duplicate of #2759 and #1845

**Comment by JohnnyDeer** [comment] 2021-02-04 09:14
I´m closing as duplicate.

**Closed as completed by JohnnyDeer** 2021-02-04 09:14 UTC
Labels: enhancement
