### ISSUE TITLE
3.3.0-830 Mk2.5 Does not show used filament under statistics while printing

### ISSUE THREAD

**Issue by stsfin** [prusa3d/Prusa-Firmware#931] opened 2018-07-17 03:52 UTC
3.3.0-830 Mk2.5 Does not show used filament under statistics while printing the counter stays on zero. Toggling the filament sensor on or off does not do anything.

Also printtime counts downwards from the ETA, and does not show the time that has passed.
![20180717_064916](https://user-images.githubusercontent.com/558170/42795615-e64162ba-898d-11e8-92a3-62bfbbaf1894.jpg)

**Comment by PavelSindler** [comment] 2018-07-17 07:10
There was bug in filament used. It was fixed in PR https://github.com/prusa3d/Prusa-Firmware/pull/919 and is present in 3.3.1 firmware version. We will look closer on print time. Thank you for reporting this.

**Comment by mkbel** [comment] 2018-09-19 13:56
I am unable to reproduce problem with "Print time :"
Can you share gcode causing the problem?
Or if it is not possible then:
slicer version
slicer settings
approximate printing time of the object
How long it took the problem to manifest itself?
any preconditions

**Comment by mkbel** [comment] 2018-09-19 14:25
Reproduced, print time overflows if greater than 9.1 hours.

**Comment by mkbel** [comment] 2018-09-19 14:27
Duplicate with https://github.com/prusa3d/Prusa-Firmware/issues/1151

**Closed as completed by mkbel** 2018-09-19 14:27 UTC
Labels: bug
