### ISSUE TITLE
[BUG] Filament sensor recognition with MK3S MMU2S unclear

### ISSUE THREAD

**Issue by kazoob** [prusa3d/Prusa-Firmware#2823] opened 2020-09-06 16:33 UTC
**Printer type** - MK3S
**Printer firmware version**-  3.9.1-RC1
**Printer filament sensor revision** - Black PCB

**MMU Upgrade** - MMU2S
**MMU upgrade firmware version** 1.0.6

**SD card or USB/Octoprint**
N/A

**Describe the bug**
Filament sensor recognition procedure for MK3S MMU2S does not indicate whether filament should be loaded to the extruder or the nozzle, nor will it prompt you with instructions to do so during the procedure. It will fail (detect type as "unknown") if filament is not loaded to the nozzle prior to launching the self test.
  
**To Reproduce**
Filament was not loaded to the extruder or the nozzle. Ran the self test (as per 3.9.0 release notes) in order to run the filament sensor recognition procedure for MK3S MMU2S. When the procedure ran there was no indication that filament needed to be loaded or unloaded nor did it prompt me with instructions. The filament sensor recognition procedure finished but the type was still "unknown".

I loaded filament to the nozzle and repeated the self test. This time the Filament sensor recognition procedure completed successfully and detected the type as "0.3 or older".
  
**Expected behavior**
Instructions on whether to load or unload filament before running the filament sensor recognition procedure, or instructions to do do during.
  
**G-code**
N/A

**Video**
N/A

**Comment by JohnnyDeer** [comment] 2021-02-04 09:10
This issue is duplicate of #2661. I´m closing.

**Closed as completed by JohnnyDeer** 2021-02-04 09:10 UTC
Labels: bug
