### ISSUE TITLE
Tiny bug found in 3.5.3 and 3.7.0-2201

### ISSUE THREAD

**Issue by DonMathi** [prusa3d/Prusa-Firmware#1728] opened 2019-04-13 09:05 UTC
Hi Prusa

I found a small bug in the 3.5.3 and 3.7.0-2201 firmware.
When you long-push the nob to raise the extruder, then:
When you want to go back to the main menu, but accidently makes a long-push instead of just a short push the nob doesn't respond to any push any longer.
I was able to take the SD card out, and put it back in, and then got back to the main menu that way.

Best regards
Kjeld

**Comment by ochm** [comment] 2019-04-13 10:55
Yes, exactly.

**Comment by Panayiotis-git** [comment] 2019-04-13 14:32
Check https://github.com/prusa3d/Prusa-Firmware/issues/1196

**Comment by mkbel** [comment] 2019-04-14 17:59
Duplicate of #1196

**Closed as completed by mkbel** 2019-04-14 17:59 UTC
