### ISSUE TITLE
[BUG]Scrolling in XYZ calibration too fast

### ISSUE THREAD

**Issue by bladel** [prusa3d/Prusa-Firmware#2645] opened 2020-04-29 16:59 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK3S
**Printer firmware version**-  3.9.0-RC3

**MMU Upgrade** - No
**MMU upgrade firmware version No

**Describe the bug**
Screen message over 3 screens scrolls too fast in XYZ calibration.
  
**To Reproduce**
Start XYZ calibration until message appears
  
**Expected behavior**
 Slower scrolling
  
**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.

**Video**
https://drive.google.com/open?id=1TTFDEPdQaKQYRU8DXZzShttutrbS84uC

**Comment by leptun** [comment] 2020-04-29 17:03
Wow. Did you do a factory reset or did you just run XYZ calibration from the menu?

**Comment by leptun** [comment] 2020-04-29 17:09
Nevermind. Ignore my last question. Can you consistently generate the issue or is it occasional?

**Comment by bladel** [comment] 2020-04-30 16:55
No works fine now after multiple reboots.

**Comment by 3d-gussner** [comment] 2020-05-02 08:25
@bladel As you cannot reproduce the issue and we didn't see that in any tests we did, would it be okay for you to close this issue?

If that kind of issue popups again we can reopen it or refer to your issue.

BTW thanks for testing the RC3 and reporting back, all feedback is welcome (hope we get once an issue that says `Everything is working`) 😉

**Comment by bladel** [comment] 2020-05-05 07:49
Yes please close it.

**Closed as completed** 2020-05-13 10:35 UTC
Labels: bug
