### ISSUE TITLE
[BUG] Logitec C920 wont connect with prusa connect

### ISSUE THREAD

**Issue by Kaylaheart** [prusa3d/Prusa-Firmware#4789] opened 2024-10-12 17:18 UTC
### Printer model

MK3S/+

### MMU model

MMU3

### Firmware versions

6.1.3+7898

### Printing from...

PrusaConnect

### Describe the bug

so. yesterday my MK3s+ with MMU2 upgraded to MK4s with MMU3, webcam Logitech HD Pro Webcam C920. stopped working i reached out to Prusa help but they just pointed to the fact that they havent updated the list for the MK4s compatible webcams and left it as that. anyone else who has this issue please let me know i will try to fix this issue and report back what i find. this is listed as MK3S/+ model but its for MK4S models. next time im buying a BAMBU LABS 3D printer. not this overpriced garbage.

### How to reproduce

connect camera with Logitech HD Pro Webcam C920 on prusa connect

**Comment by Prusa-Support** [comment] 2024-11-01 15:18
Thanks for bringing this to our attention, however, _this is not the right repository_ for this issue and _this is not a bug_.

As explained in the [relevant Help guide](https://help.prusa3d.com/guide/camera-setup-for-prusalink-prusa-connect_470943), RPi-compatible cameras are only compatible via Raspberry board, which is not needed in case of new Prusa printer provided of Buddy boards - unless you want to run other serial terminals like Octoprint.
In other words, this is the expected behavior (technically, a bug).

Also, this repository is not the correct one to discuss this issue because this repository is only relevant for old Prusa printers with RAMBo boards. You may want to reformulate and discuss these features in https://github.com/prusa3d/Prusa-Firmware-Buddy or https://github.com/prusa3d/Prusa-Link-Web/ as the issue has to do with the compatibility of Prusa Link with new Buddy boards b again, this is not a bug.

This issue will be closed as not valid now.

Michele Moramarco
Prusa Research

**Closed as not planned by Prusa-Support** 2024-11-01 15:18 UTC
Labels: invalid

**Comment by Kaylaheart** [comment] 2024-11-04 11:41
then why did prusa help say it was?

**Comment by Kaylaheart** [comment] 2024-11-04 11:56
and its not a RPI- Camera

**Comment by Prusa-Support** [comment] 2024-12-28 11:09
> then why did prusa help say it was?

Please check the relevant steps in the instructions linked above.
You will find a short description of the compatibility conditions as well as a link to the list of _known_ compatible cameras.
> and its not a RPI- Camera

If a camera is listed then it should be safe to call it "_RPi-compatible_", hence _compatible for MK2.5/3 with Prusa Link via Raspberry boards_, whereas `Raspberry board ≠ Buddy board`, and RPi boards are not required for MK4/XL/MINI.

Everything looks correctly stated in the Help section to me but, if anything looks incorrect or unclear, please add a comment _directly in the Help section_ under the relevant guide/step.

This issue should be considered invalid as per https://github.com/prusa3d/Prusa-Firmware/issues/4789#issuecomment-2452053758.

Michele Moramarco
Prusa Research

**Comment by Kaylaheart** [comment] 2024-12-28 13:26
You realise the camera is hooked up to my computer not the printer itself
right? The purse connect stopped working after I refreshed the prusa
connect page. I don't understand how after upgrading my printer from mk3 to
mk4 and using the camera successfully with the mk4 using prusa connect it
suddenly without explanation just stopped connecting.
