### ISSUE TITLE
Menu -> Preheat -> Nozzle Change

### ISSUE THREAD

**Issue by JoeyMarkowitz** [prusa3d/Prusa-Firmware#3539] opened 2022-07-09 22:27 UTC
It would be helpful to include a Nozzle change preheat setting configured to only heating the nozzle to 285 deg C as per instructions for changing the nozzle in the following youtube video by Prusa.

https://www.youtube.com/watch?v=txt6sxV6X88

**Comment by Prusa-Support** [comment] 2022-07-19 15:54
This issue will be closed as a duplicate of #2972.

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2022-07-19 15:54 UTC
Labels: feature request, HW issue, temperature, materials
