### ISSUE TITLE
3.8.0 firmware causing X-axis motor to constantly crash extruder into x-home

### ISSUE THREAD

**Issue by makermelissa** [prusa3d/Prusa-Firmware#2282] opened 2019-10-19 02:42 UTC
I have experienced this a number of times and it seems this is how it usually happens.
1. Print something after turning on printer
2. Go to print something else
3. The hotend does not heat up and it remains in a "heating..." state
4. Go to Stop Print
5. Extruder goes crashing into side

Printer: Prusa MK3/S with MMU2S
Printing in Single Filament mode
Firmware version 3.8.0

**Comment by makermelissa** [comment] 2019-10-19 02:47
Here's a picture of the heating issue before the crash:
![IMG_1067](https://user-images.githubusercontent.com/2681417/67136760-e005fa80-f1df-11e9-8c7f-3f95c548b083.jpeg)

I knew once I saw this the crash would definitely happen.

**Comment by makermelissa** [comment] 2019-10-19 02:59
Oh yeah, one other thing is I didn't seem to have this problem until I put the gcode files a couple levels deep inside folders.

**Comment by leptun** [comment] 2019-10-19 05:09
Please try using 3.8.1-RC1. The problem might be fixed there.

**Comment by makermelissa** [comment] 2019-10-19 05:11
Ok, I'll give it a go.

**Comment by leptun** [comment] 2019-10-19 05:20
Out of curiosity, did you take the SD card out between prints? If yes, then that’s the exact issue I fixed recently and should be present in 3.8.1-RC1.

**Comment by makermelissa** [comment] 2019-10-19 05:46
Yes I did.

**Comment by tibahut** [comment] 2019-10-19 08:09
I had the same issue with SD card removal and print stop combo.
I can confirm the issue is fixed with the 3.8.1-RC1.

Thanks @leptun

**Closed as completed** 2019-10-24 20:17 UTC
Labels: FW 3.8.0
