### ISSUE TITLE
M73 Time Remaining not working when print over 12h

### ISSUE THREAD

**Issue by TheZeroBeast** [prusa3d/Prusa-Firmware#1008] opened 2018-08-05 03:59 UTC
Hello,
I'm running MK3 on 3.3.1 and Slic3r 1.41.0Alpha3 and when a print is over 12h I get the excess displayed counting down to 12h remaining which then starts counting down the final 12h.

The attached gcode has M73 commands correct showing 18h in number of minutes so it appears to not display correct on MK3 at present.

[FEDAIM-Case-Front_0.2mm_ABS_MK3.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/2260033/FEDAIM-Case-Front_0.2mm_ABS_MK3.gcode.zip)

Thanks,
Rob

**Comment by 3d-gussner** [comment] 2018-08-05 06:07
Maybe there is an issue with values above 1024 as 18h x 60m is 1080...would be interesting to generate a gcode running for 17h (under 1024min) to prove it.

**Comment by TheZeroBeast** [comment] 2018-08-05 07:08
![62e48ae7-3460-4111-80cf-613bd3cca043](https://user-images.githubusercontent.com/20939095/43683567-f732c35e-98d1-11e8-9f45-c026659a2b55.jpeg)
Here is that gcode 3h into the 18h print so might not be a variable limit as the sole cause. 🤔

**Comment by RacingHell** [comment] 2018-08-07 22:01
Can confirm this. A 14h40m print starts counting at roundabout 3 hours remaining.

**Comment by 3d-gussner** [comment] 2018-08-08 04:45
For me it looks like 12h is the point of turn, as @RacingHell has a 14h40m print starts counting opposite direction around 12h into the print ...14h40m - ~3h = ~12h

**Comment by TheZeroBeast** [comment] 2018-08-09 03:35
I’d say this commit will solve the issue. Will need to test.

https://github.com/prusa3d/Prusa-Firmware/commit/990a5c9119b2515d265ecb10f745371f2fee3cbb

**Comment by middelink** [comment] 2018-08-09 07:08
This is dupe of #986

**Comment by Prusa-Support** [comment] 2022-05-06 11:59
This issue will be closed as a duplicate of issue #986.

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2022-05-06 11:59 UTC
