### ISSUE TITLE
Translated UI breaks Octoprint file list from SD-Card

### ISSUE THREAD

**Issue by benderl** [prusa3d/Prusa-Firmware#926] opened 2018-07-13 23:08 UTC
After flashing latest firmware (3.3.0-830) I switched the UI to german. I then realized, that Octoprint (1.3.8 on OctoPi 0.15.0PE) does not list any SD-Card contents. Switching back to english solved this problem. I think, that Octoprint scans the response for "Begin file list" and "End file list". So these strings must not be translated.

**Comment by sekuch** [comment] 2018-07-19 15:02
duplicate of #926

**Closed as completed** 2020-07-08 17:12 UTC
