### ISSUE TITLE
  [ENHANCEMENT] Add "Cancel" to Filament List when printing on MMU

### ISSUE THREAD

**Issue by brettvitaz** [prusa3d/Prusa-Firmware#2756] opened 2020-06-22 17:24 UTC
**Printer type**
MK3S

**MMU Upgrade**
MMU2S

**Is your enhancement related to a problem? Please describe.**
When starting a MMU print, there is a chance that the necessary filament has some issue and the print needs to be canceled. This happens often enough for me that it would be very nice to have "Cancel" as the last option for Filaments, just like when doing First Layer Calibration.

**Describe the solution you'd like**
Add "Cancel" to Filament options for MMU prints.

**Comment by scooper4711** [comment] 2020-06-27 23:17
Yes. I dislike having to press the reset button so often with the MMU2S.

**Comment by JohnnyDeer** [comment] 2021-02-04 08:39
This issue is duplicate of #2411. I´m closing.

**Closed as completed by JohnnyDeer** 2021-02-04 08:39 UTC
Labels: enhancement
