### ISSUE TITLE
Printer pauses during printing

### ISSUE THREAD

**Issue by TheZippyMan** [prusa3d/Prusa-Firmware#545] opened 2018-03-10 17:34 UTC
Hello,

today I discovered, that my printer sometimes just pauses during printing from SD. The display then shows "Heating done" on the LCD then continues printing after a second.
Filament Sensor on, Fan Sensor on, all other features are disabled.
Prusa i3 MK3 on 3.1.2.

Do you have a solution for this?

Justin

**Comment by ProgrammScotty** [comment] 2018-09-27 15:35
I have the same problem after updating to FW 3.4. It happens during very short movements (zig zag). It seems to me, that the printer runs out of commands. Filament sensor on, Fan monitoring on, everything else disabled! I am printing from the SD card.

->>> The reason was the filament sensor. But why I received no error message? Only the status message Prusa Mk3 ready

**Comment by avzhatkin** [comment] 2018-10-08 05:39
Hi! I got similar behaviour, but it seems to be connected to heating. When filling big areas, it drops 2-3 degrees below target temperature and waits a little for the hotend to heat up.

**Comment by tobiasneumann** [comment] 2018-11-12 19:40
I experience the same behaviour.
And I see the same message "Prusa Mk3 ready", but the temperature isn't dropping during that or just before that (neither nozzle nor bed).

**Comment by dancorrigan1** [comment] 2018-11-28 01:41
Same issue on 3.5.0, Just upgraded yesterday. I'm using MMU 2.0 also. I am seeing this behavior through a MMU Single print though. Much like described in an earlier post, "It happens during very short movements (zig zag)" .. Do you know K's Blaster Blade Runner gun on Thingiverse? Yup.. That one. Another MK3 Kit I have prints it flawlessly. Prusa built is failing me often now, especially since the addition of my MMU, but I digress. 

Most of the posts I've found on the internet that show this behavior all suggest the failure is caused by the filament sensor and the associated fix is to disable it. Ugh.

**Comment by transplier** [comment] 2018-12-09 20:57
Started happening to me using the MK3 fast profile. I don't have the MMU. Printer just pauses for a few seconds, while showing `Heating...` on the screen. The gcode had just finished some slightly complex geometry but the last few commands were long straight lines so I don't think it's a command buffer issue. This particular filament (MakerGeeks White Hot HTPLA) was giving me issues with the filament sensor earlier, so I turned it off. It hasn't happened since.

Addendum: I tried autoloading the white filament in question and it took me several tries to get the machine to recognize that the filament was inserted. Seems to reinforce the filament sensor idea.

**Comment by stevegg** [comment] 2019-01-06 20:18
Same here.  Just got this today.  Seems to be happening during the infill of a narrow section with a rectilinear pattern.

**Comment by transplier** [comment] 2019-01-06 21:08
Update from my side. I've got at least a hundred hours of smooth printing since my last post. Nothing has changed apart from using different filaments.

**Comment by emreerokyar** [comment] 2019-01-11 12:19
I am experiencing the same issue on my MK3 (kit version) with FW **`3.5.1-1778`** and Slic3r **`1.41.2+`**.

My MK3 stops moving and extruding in the middle of the print, says **`Prusa i3 MK3 ready.`**, then **`Heating.`** and continues after a few seconds (_see the photos below_).

The temperature fluctuation is pretty minor (1 to 2 ℃ off from target at most), or on some occasions, completely non-existing during this behaviour. I've seen much major deviations (3 to 5 ℃ off from the set target) **without** this behaviour in the past, so I don't think that the reported temperature (_the one that is visible on the LCD_) has any direct contribution to this issue, but of course, it can be causing this in-directly - feel free to discuss it.

Something I noticed is that this has a higher chance of being triggered with prints that are causing a lot of repetative retractions in a relatively short duration - think of like successive retractions for a whole minute or so.

Another thing is that the occurance of this issue doesn't seem to be random at all, as if I recall correctly, this has happened twice with the same object while printing and then, did not happen with other objects for a while - until it happened again on another object today. So I think it should be reproducable at will, yet I did not find the time to test and verify this behaviour. I'll update this post with my results if I can find the time to test it.

I'm sharing the object ([MainStage_4p71_Hex12_Tol40_V04.stl.zip](https://github.com/prusa3d/Prusa-Firmware/files/2761627/MainStage_4p71_Hex12_Tol40_V04.stl.zip)), my Slic3r settings ([config.ini.zip](https://github.com/prusa3d/Prusa-Firmware/files/2761670/config.ini.zip)) and the generated actual G-code ([MainStage_4p71_Hex12_Tol40_V04_19m_57g_6try_9h35m - 1.3.0.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/2761677/MainStage_4p71_Hex12_Tol40_V04_19m_57g_6try_9h35m.-.1.3.0.gcode.zip)) I used that caused this issue - in case someone decides to further pursue this issue for debugging.

Below are the photos of the issue while it's happening;

![Printing...](https://user-images.githubusercontent.com/11826350/51033328-1d37bf00-15b4-11e9-91b5-46994e19c71d.jpeg)

![Prusa i3 MK3 ready.](https://user-images.githubusercontent.com/11826350/51033334-22950980-15b4-11e9-8cae-a942a8e99ae0.jpeg)

![Heating...](https://user-images.githubusercontent.com/11826350/51033339-258ffa00-15b4-11e9-9da2-11b979b535a3.jpeg)

Hope this issue gets some traction since it has started to bother me due to its frequency.

Please also note that this has a negative affect on the printed part's quality, as the hot nozzle sits on top of the printed part at the same spot for a few seconds, melting down the part and creating some kind of a crater at that point.

**Comment by alexbystrow** [comment] 2019-01-15 22:06
A few days ago I activated the filament sensor on my MK3 for the 
first time. Just for the convenience of filament auto loading.
Since then I just printed some calibration cubes. Had no issues.
But today I started to print a bigger model. Suddenly after a few
minutes the printer paused for about 3 seconds and continued.
The display showed "heating..." I didn't get the "MK3 Ready" message.

Then the frequency of this behaviour increased until it stopped several
times a minute. The display showed a maximum temp. drop of 1°C, so 
the thermistor should be fine.

I tried the same print several times. Failed each time.
In between I printed another calibration cube and it printed fine.

One time, with the larger print, out of a sudden the printer registered
 a false filament runout. 

Just now I found this issue and disabled the **filament sensor.**
What should I say, that **fixed it!**
I am running 3.5.0 and the sensor was the only thing I changed.

edit:
I was printing with white PLA.
In my opinion the filament sensor could have some issues because of the increased number of retractions.

**Comment by emreerokyar** [comment] 2019-01-15 22:20
@alexbystrow, thanks for the tip! That is indeed worth trying. I am also printing with white PLA...

I also remember myself reading somewhere else that a few other people also pinned it down to the false readings from the filament sensor after upgrading the firmware level to **3.5.0** (if I recall correctly), and somehow causing this issue in the end.

Will definitely give it a try, and hope it gets fixed soon!

**Comment by mmcglumphy** [comment] 2019-02-13 02:33
Same issue for me.  Pause... Heating... Resume... Repeat a few minutes later. 

This kills tiny prints. The pause stops the head right on the print and when it resumes, extra liquid plastic is left behind and essentially gets smeared into the subsequent layers.

Disabled the filament sensor and the problem goes away. I also have random issues getting filament to detect and load. Reproduced using two different brands of gray. Latest firmware.

**Comment by uniacke1** [comment] 2019-02-13 02:43
I wonder if this is the source of #1522 as well then. Though I explicitly checked the menu for filament runouts and it reported zero.

**Comment by mmcglumphy** [comment] 2019-02-13 05:23
Very possible they are all related, though for me the problem definitely goes away if I disable the sensor.

The blob at the end of the stroke in that screenshot in #1522 looks very similar to artifacts I was seeing in some of my prints.

**Comment by PavelSindler** [comment] 2019-02-18 15:45
If printer detects possible filament runout, it pauses print immediately and move filament back and forth and measures response. If it decides that filament is still there, print is then resumed and "Heating..." will appear for a while.
Cleaning your sensor may help in some cases.

**Comment by Crunch69** [comment] 2019-03-03 00:29
I have the same problem it is the filament sensor turn it off and then try printing

**Comment by ezeackermann** [comment] 2019-03-26 17:15
the only firmware that work fine is 3.5.1. The next releases have the temperature fluctuation. Also I see that the heated bed are more time on with the latest releases. I see this in the powermeter of my UPS.
Downgrade the machine and you will see the difference.

**Comment by hutje** [comment] 2019-04-01 08:36
Same problem with 3.7.0-RC1. Got multiple stops. Mostly the same place on the gcode. I use Slic3r PE 1.41.2. Tried to print from SD card with or without OctoPrint connected, also Octoprint with or without sd card inserted. This caused a few changes, but eventually the print stops after doing the perimeter.
The three prints in the picture happened all with the same circumstances, printing from OctoPrint, SD card was inserted.
Without SD card inserted it went to 7.0mm layer and then stopped.
Printing from SD Card and without OctoPrint connected to the printer it went to 2.4mm layer and then stopped...

Printing with 0.6mm nozzle
Zip contains: Gcode and 3mf file.
[Sparschwein_repaired_0.4mm_PLA_MK3.zip](https://github.com/prusa3d/Prusa-Firmware/files/3028421/Sparschwein_repaired_0.4mm_PLA_MK3.zip)
![image](https://user-images.githubusercontent.com/15308350/55314484-879d2480-546a-11e9-8932-afa07b59a142.png)
![image](https://user-images.githubusercontent.com/15308350/55314499-8e2b9c00-546a-11e9-9186-778e689ef436.png)
![image](https://user-images.githubusercontent.com/15308350/55314579-bc10e080-546a-11e9-823d-077970839af9.png)
![image](https://user-images.githubusercontent.com/15308350/55314595-c501b200-546a-11e9-810a-db7491e1cbe5.png)
![image](https://user-images.githubusercontent.com/15308350/55314610-cdf28380-546a-11e9-9eed-347fe3030289.png)

**Comment by Prusa-Support** [comment] 2022-06-06 08:42
Hello! I am absolutely sorry for the late response to this thread. I see this was quite old and I believe this should have been fixed from 3.9.x firmware onwards. In case you are still experiencing similar issues at this time, can you please let me know via email? info@prusa3d.com mentioning me in the subject - I'll review each case in more detail this way. Closing the issue for now based on this info. 

Alessandro Pantaleo
Prusa Research

**Closed as completed by Prusa-Support** 2022-06-06 08:42 UTC
