### ISSUE TITLE
[BUG] PAUSE PRINT feature

### ISSUE THREAD

**Issue by rosauro3d** [prusa3d/Prusa-Firmware#3323] opened 2021-12-20 00:43 UTC
3D printer brand / version + firmware version 
Prusa MK3S, firmware 3.10.0 and 3.10.1

Slicer
PrusaSlicer - Tested with 2.3.1, 2.3.2, 2.3.3

Operating system type + version
Windows 10 Pro, versioni 20H2

Behavior
In the Prusa slicer a PAUSE PRINT was added so that I could embed a nut to a project.

When the print job gets to that point of PAUSING and after adding the hardware I select resume print.
After selecting resume print the screen goes blank for 30 seconds.
The nozzle's temperature continues to drop as the print head continues with the job.
At the same time there is no filament being fed through the nozzle.

I've already reported this with Prusa support back in July 7, 2021.
I've done everything they've instructed me to do. (reflashing firmware, generate new gcode, redownload firmware files, full system refresh, tried slicers 2.3.1, 2.3.2 and 2.3.3, tried Pronterface, tried via SD, generate new gcode for a new project)
I thought the new firmware 3.10.1, that was release a few days ago, would have resolve this issue. Apparently not.
I was told by Prusa support that they will report the issue again and to also report it here as well.

For now I've gone back to firmware 3.9.3 where the PAUSE PRINT last worked.

There is a video I made of the issue that can be viewed here:
http://rosaurophotography.com/misc/videos/prusapause/

**Comment by gudnimg** [comment] 2021-12-20 09:23
I can try to reproduce this on my end (on MK3S+). But I’ve not used this feature before. Do you configure the pause in Prusa Slicer?

I think we should focus on fw v3.10.0

I’m currently printing a 2 day print which finishes tomorrow.

**Comment by 3d-gussner** [comment] 2021-12-20 11:38
@rosauro3d have you searched the github for your issue? I think you have the same issue as https://github.com/prusa3d/Prusa-Firmware/issues/3148 describes.

Please read https://github.com/prusa3d/Prusa-Firmware/issues/3148#issuecomment-855201971
and https://github.com/prusa3d/Prusa-Firmware/issues/3148#issuecomment-966463702

Let us know if that helped.

**Comment by rosauro3d** [comment] 2021-12-20 23:17
@gudnimg Yes you configure the pause in Prusa Slicer.  
Check out this video:  https://www.youtube.com/watch?v=CtC5vAK94qA

@3d-gussner Yes I saw that back in July.  It's a temporary solution.  I'm looking for a permanent solution.  I would have thought by 3.10.1 firmware that the issue would have been addressed.

**Comment by 3d-gussner** [comment] 2021-12-21 12:55
@rosauro3d There is this working solution, please use it.

I don't know if or when there will be a different solution.
Implementing a host/printer negotiation doesn't sound easy and resource friendly.

The Prusa team is always fighting and improving code to free up resources. There are few feature requests which will consume these limited resources and it is hard to decide which will be included which not.

As M601/M602/M603 with minor modifications in Octoprint is working the chances are high that other features will get a higher priority.

**Comment by rosauro3d** [comment] 2021-12-21 20:38
@3d-gussner 
"There is this working solution, please use it." - No thank you.

Are you saying that Prusa intentionally created a bug so that other feature requests can be implemented?    LOL

That's like saying your vehicle manufacturer disabled your headlights to be able to implement new features.  Then asks you to use a flashlight as a solution...  ...because the development of warp speed has a higher priority....

I will continue to use 3.9.3.

**Comment by gudnimg** [comment] 2021-12-21 21:23
I can clearly see this issue in your video as well https://github.com/prusa3d/Prusa-Firmware/issues/3316

I’m thinking a one layer print should be enough to reproduce this. I will add a comment here if I find anything interesting in the next days.

**Comment by gudnimg** [comment] 2021-12-22 12:15
@rosauro3d Could you try and see if the issue appears with this small gcode file. Only takes about 1 minute. The printer will stop after the first layer.
[test_file.zip](https://github.com/prusa3d/Prusa-Firmware/files/7762518/test_file.zip)

I could not reproduce this issue on FW 3.10.1 with PrusaSlicer 2.4.0, I don't think the slicer version should matter.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/8218499/147091215-00bbe4ae-2558-4480-b2e6-7409b682a40d.png">

**Comment by rosauro3d** [comment] 2021-12-22 20:29
@gudnimg 
I tested your GCODE with FW 3.10.1.  
Here's the [video](http://rosaurophotography.com/misc/videos/prusapause/index.html#gilbert).

**Comment by gudnimg** [comment] 2021-12-23 11:29
I am able to trigger the issue where extruder temperature is not rising afte resuming and LCD still displaying "Print paused" if this lines is hit https://github.com/prusa3d/Prusa-Firmware/blob/0be90dc5d1d8b6b12e063b751c7e16486520ba98/Firmware/ultralcd.cpp#L6390

Though I do not get this 30 second long blank screen, and my printer stays still.

Edit: There is no difference between `fan_error_selftest()` in 3.10.0 and 3.9.3 so I doubt that is the source of the issue.

**Comment by gudnimg** [comment] 2021-12-23 14:40
@rosauro3d Are you using Octoprint? If I understand the workaround @3d-gussner correctly it only affects Octoprint?

**Comment by rosauro3d** [comment] 2021-12-23 22:17
@gudnimg 

This is already a known firmware issue with Prusa.  I’ve brought this up with them back in July.  I brought it up to their attention again upon the release of FW 3.101.  The only reason I posted it here is that Prusa support had asked me.  I’m assuming it’s to make everyone else aware and/or to expedite the remedy with the developers.  The temporary fix, in Octoprint (M601 and M602), does work but the issue still remains as it’s clearly evident with the release of FW 3.10.1.

**Comment by JohnnyDeer** [comment] 2022-02-15 11:30
@rosauro3d I got info from our Tech Support that this issue was clarified via email, is that right?

**Comment by rosauro3d** [comment] 2022-02-15 16:23
Hi Johnny

Yes it was clarified that the issue won't be fixed any time soon.  It will
be an ongoing issue.


Regards

Rosauro

**Comment by agners** [comment] 2022-02-27 09:58
Encountered the same issue on a MK3S with FW 3.10.1/PrusaSlicer 2.4.0. Inserted printer pause to pause printing during the night using the "Add pause print (M601)" command in PrusaSlicer. In the morning, pressing the Knob -> `Resume` resumed printing, but tool temperature stayed off (Bed temperature stayed on the whole time, which I think is correct). This is not what I would expect from a pause print command. I am using OctoPrint, but resumed printing using the Knob. I was able to set temperature in OctoPrint, but some part of the layer is now missing. 

Also the display stayed blank since selecting `Resume` (it did not come back even when turning the knob/waiting for more than 30 minutes now). So far, the printer seems to continue fine with the display being blank.

**Comment by rosauro3d** [comment] 2022-04-21 22:47
Issue still the same with firmware 3.11.0

**Comment by gudnimg** [comment] 2022-04-21 23:29
I wonder if the issue is with `lcd_resume_usb_print()`. It would be interesting to change `lcd_resume_usb_print` in the line below to `lcd_resume_print` to see if that fixes the issue. I don't think this will fix the issue where the hotend is turned off, but the display should not go blank.

![image](https://user-images.githubusercontent.com/8218499/164566650-9c28520c-18e4-4cce-b5d8-10bd173078ff.png)

I'm thinking this because `lcd_resume_usb_print()` is basically empty. I highly suspect the issue is related to `lcd_draw_update `not being set. If the status menu appears after exactly 30 seconds, then that would confirm it as there is a timer which will expire when there is a 30 second inactivity within the LCD menu and will force the LCD status screen to be re-drawn.

I am unfortunately unable to test this as I can't print over USB.
![image](https://user-images.githubusercontent.com/8218499/164566610-a79c7ea9-3b44-4b68-bf01-f83c36e67ab6.png)

**Comment by rosauro3d** [comment] 2023-01-17 18:35
Firmware 3.12.0 fixed this issue.
M601/602 no longer required.

**Closed as completed** 2023-01-17 18:36 UTC
Labels: bug
