### ISSUE TITLE
XZY Cal failing on the 3.2.0 RC1 

### ISSUE THREAD

**Issue by alientek** [prusa3d/Prusa-Firmware#625] opened 2018-04-13 19:26 UTC
Something is wrong, it aint working.

**Comment by grumpyburton** [comment] 2018-04-13 21:02
Also having issues. Plus getting warning messages "Warning: both printer type and motherboard type change". This was using  prusa3d_fw-3.2.0-RC1.461-1_75mm_MK3-EINSy10a-E3Dv6full.hex on mk3

**Comment by kaycet** [comment] 2018-04-15 01:17
I've also had this issue. Rolled back to previous release to continue using printer.

**Comment by blgli** [comment] 2018-04-15 05:30
Having the same problem on my MK3. I have one of the early MK3’s delivered in December of 2017 if it matters. It will find the first point but continually fails on the second calibration point. This is without the steel sheet on. Manually moving the PINDA over both front calibration points triggers the PINDA but it will not calibrate. Keeps failing after the second point. I have moved the PINDA higher and lower, no change with calibration point 2. Sometimes depending on the PINDA height it would fail on the first point.

**Comment by Jacks3DPrinting** [comment] 2018-04-15 13:25
yesterday the xyz calibration (R3.2.0) it worked. 
After tensioning the belts a little (y226 x255) it fails after the 4th point. 
The PINDA probe triggers over all points when i do the bed mesh leveling. 

Hope a release for the major problems come soon.

**Comment by TheZippyMan** [comment] 2018-04-15 21:48
+1 on this, also having this problem. Fails on second point...

**Comment by ctilley83** [comment] 2018-04-15 23:57
Having the same error.  Calibrated the first time but gave strange result for skew.  Before calibration I was .05-.07.  After I was at .35.  Factory reset, then ran self test. Failed a few times on different points.  Most on the 4th point, but a few on the 1st, 2nd, and 3rd

Test number
1: .35
2: failed point 4
3: failed point 4
4: failed point 4
5: failed point 1
6: failed point 2

Another factory reset and self test

7: .13
8: .17

**Comment by ghost** [comment] 2018-04-16 05:01
My skew according to every previous version of the firmware was 0.02 degrees on my MK3.

According to the first run of the XYZ calibration on 3.2.0 RC1, my skew was 0.38. The second time I tried, it was 0.24 degrees. I cleared the XYZ calibration and ran it for a 3rd time, and I got a skew of 0.10. I ran it for a 4th time (without reclearing the calibration) and I got a skew of 0.13. I did a full factory reset, ran the calibration again, and got 0.35 degrees.

Visually, it appears that my PINDA is much higher off the bed that it was in previous versions of the firmware while doing the calibration. I assume the precision of the PINDA is inversely proportional to distance, so I'd suspect that may be the cause of the inconsistent and incorrect calculations I'm seeing.

**Comment by PavelSindler** [comment] 2018-04-16 09:27
Thank you for your feedback. New xyz calibration is very very different from the old one - it is radical change, but it has many advantages. We tested it pretty well on many MK3 and MK2.5 printers and it seemed reliable, unfortunately it seems that there are still some printers, where it doesn't work and new calibration still needs some "fine tuning". If you want to help us, please send serial log from failing xyz calibration here.

**Comment by ctilley83** [comment] 2018-04-16 14:16
@PavelSindler I've done some testing and I'm getting strange results.  When I run calibration by sending M45 through Pronterface, I get rather consistent results. .07, .10, .09, .09

When I run xyz calibration from the printer itself unplugged from USB, I get much more varied results.  .04, .15, .08 and .12

heres a link of the pronterface console output of the calibrations mentioned above.
[Calibration Zip](http://www.hermeswebservices.com/xyz_cals.zip)

**Comment by codiac2600** [comment] 2018-04-16 14:30
I've failed every single XYZ calibration since updating. Usually the 3rd point which it finds just fine. 

[Fail One.pdf](https://github.com/prusa3d/Prusa-Firmware/files/1915715/Fail.One.pdf)

**Comment by codiac2600** [comment] 2018-04-16 14:47
Passed for the first time using @ctilley83 technique of Pronterface, disabling temp calibration, and a strong drink.

**Comment by codiac2600** [comment] 2018-04-16 15:53
I'v been running a bunch of XYZ calibrations and it's not consistent. Still fails the majority of times but better than previously. 
[Fail Two.pdf](https://github.com/prusa3d/Prusa-Firmware/files/1916119/Fail.Two.pdf)
[Fail 3.pdf](https://github.com/prusa3d/Prusa-Firmware/files/1916120/Fail.3.pdf)

**Comment by ctilley83** [comment] 2018-04-16 22:18
After a few more calibrations, I'm starting to believe that the theory on pronterface is just coincidence. Here's an excel file of 5 runs of calibration. I pulled the data from computed x y values for each point.

[Calibration Data](http://www.hermeswebservices.com/calibration_runs.xlsx)

**Comment by ctilley83** [comment] 2018-04-17 14:40
@PavelSindler Do you have everything you need from us to troubleshoot this issue?

**Comment by Crunch69** [comment] 2018-04-17 21:55
PavelSindler i would love to help but I do not wish to destroy my heat bed it already put a nice long scratch into it.  The nozzle dives into the bed

**Comment by cobramike** [comment] 2018-04-18 06:42
Same here after installing the new firmware. 

Bed failing on points
1
1
3
3
3
3
4
4
1
4

But after installing the old firmware its working fine.

**Comment by PavelSindler** [comment] 2018-04-18 09:59
Thank you guys for all these logs and information. We are now working on it and we will inform you as soon as possible.

**Comment by ChrisVahi** [comment] 2018-05-07 21:11
I was having similar problems and traced it to missed steps on one motor of my z axis which knocked my x axis out of alignment. I added M907 Z750 E750 to my start G code script (to set motor drive currents, I increased the extruder current because I was also getting binding from the extruder during fast infill) and have been getting better results 3 prints in.

**Comment by R3N3G4T** [comment] 2018-05-17 12:42
Hi,

I've got the same problem with the calibration on the third point, running in power mode doesn't fix it for me. I have the latest 3.2.0 Firmware installed. Running the calibration with Pronterface showed this:

```
>>>M45 V2
SENDING:M45 V2
start
echo: 3.2.0-555
echo: Last Updated: May  9 2018 19:03:26 | Author: (none, default config)
Compiled: May  9 2018
echo: Free Memory: 1668  PlannerBufferBytes: 1392
echo:Hardcoded Default Settings Loaded
adc_init
PAT9125_init:1
FSensor
ENABLED
PAT9125_init:1
echo:SD card ok
>>>M45 V2
SENDING:M45 V2
Iteration: 1
xyzcal_find_bed_induction_sensor_point_xy x=1200 y=200 z=2000
point=0 x=1200 y=700 z=2000
xyzcal_meassure_enter
xyzcal_searchZ x=1200 y=700 z=2000
xyzcal_spiral8 cx=1200 cy=700 z0=2000 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=1200 cy=700 z0=2000 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=1200 cy=700 z0=1900 dz=100 radius=-900 ad=0
xyzcal_spiral2 cx=1200 cy=700 z0=1800 dz=100 radius=900 ad=3
xyzcal_spiral2 cx=1200 cy=700 z0=1700 dz=100 radius=-900 ad=2
xyzcal_spiral8 cx=1200 cy=700 z0=1600 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=1200 cy=700 z0=1600 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=1200 cy=700 z0=1500 dz=100 radius=-900 ad=0
xyzcal_spiral2 cx=1200 cy=700 z0=1400 dz=100 radius=900 ad=3
xyzcal_spiral2 cx=1200 cy=700 z0=1300 dz=100 radius=-900 ad=2
xyzcal_spiral8 cx=1200 cy=700 z0=1200 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=1200 cy=700 z0=1200 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=1200 cy=700 z0=1100 dz=100 radius=-900 ad=0
xyzcal_spiral2 cx=1200 cy=700 z0=1000 dz=100 radius=900 ad=3
xyzcal_spiral2 cx=1200 cy=700 z0=900 dz=100 radius=-900 ad=2
xyzcal_spiral8 cx=1200 cy=700 z0=800 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=1200 cy=700 z0=800 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=1200 cy=700 z0=700 dz=100 radius=-900 ad=0
xyzcal_spiral2 cx=1200 cy=700 z0=600 dz=100 radius=900 ad=3
 ON-SIGNAL at x=890 y=289 z=543 ad=1868
sizeof(block_buffer)=1392
sizeof(total)=1080
xyzcal_scan_pixels_32x32 cx=1200 cy=700 min_z=471 max_z=2400
0f000000000000052328200000000000000000000000192d1f39412d243e3f2a
0f00000000000009201f000000000000000000000000101e232a3d3a2b2e3734
1300000000000c170e000000000000000000000000000b2622323c2622333c2a
180000000006130c000000193044483c130000000000081d2224393c24223634
1600000000100800000a485a61657a6238210000000006272820293b1e1f3b2a
20000000030f0000001546646e787d776d500e0000000523271626382d1f3530
220900100e080000002e6f706d676d716d57120000000c20192d381f1a323620
201d000e10000000042c6262666c576373713c02000009201517312e1a22312a
2713001b0000000000336f6a585c6c5c61702a0000000619242130271e1c342a
1e16011100000000000c4c64686262676c682500000000171719322d16172a2b
1f11090a00000000000949636b6b6d695c390400000001221d1623261a162f26
171600100000000000000c39475d66604e150000000000111815202322192629
19100014000000000000000126343121000000000000011b131c2a150d242d1c
1409001000000000000000000000000000000000000000151d161b2013122721
160e050f07000000000000000000000000000000000004150d182114121f2712
12080010000000000000000000000000000000000000001d0a0e21211110241d
150f000b0000000000000000000000002b2f0f00000014140f1e25110f1e2610
1103000a0a00000022392e08000000182d3f331500000b200c0f231c10122a17
150d09150a00001631343f1900000425363420110001171d11102216071e251a
14000000160008121d22272412000e141c15161c0f0b101f0e0d1a1f11131c13
140b000a18000017140f192004000b160b0018190c07181116171e0f191d1e0d
080000001200000d13000c100c000c100c000d190c001018000f161f0e0e1a13
160b00081005000b0a00001100000f1500000f120002170e00021713151b1517
00000000000000000000001000000a1100000e1900001017000b151c080d1814
100a00070f05000a0000001000000a140400130d000012110004160c00141a0e
000000000000000d0000001100000c0f00000e13000110150d0f15110b0d1512
100900050d0400000a0000000000000000000d100000100a000e1904000f180e
0000000000000000000000000000000c000000110006110f000f120f0a0c1411
0f0900000000000000000000000000000000000000000e000000180d00081606
0000000000000000000000100000001000040e0f0a0a100e090d140f0b0f130e
0d0902000000000000000000000000000000000000000e000000110c00000f0a
0000000000000000000000000000071200030c0d07090f0f090c120d090e110e
  0 609
  1 215
  2 94
  3 45
  4 9
  5 9
  6 34
  7 9
  8 0
  9 0
 10 0
 11 0
 12 0
 13 0
 14 0
 15 0
max_c=215 max_l=1
 min=8 max=128 dif=120
0e000000000000003944330000000000000000000000244e3168794e3b737548
0e000000000000023331000000000000000000000000112e3948716a4a51645d
17000000000008200c00000000000000000000000000064037596e40375b6e48
2200000000001708000000245580886e170000000000002c373b686e3b37625d
1d00000000110000000488aebdc6f3c066350000000000424433466c2e316c48
33000000000e0000001b84c4d9eef9ecd7990c0000000039421d40664e316055
370200110c0000000051dbddd7cad7e0d7a8150000000833244e663126596233
332c000c11000000004cc0c0c8d5a8c2e4e06e00000002331b20575126375748
4217002800000000005bdbd1aab3d5b3bddd4800000000243b3555422e2a5d48
2e1d001300000000000891c4ccc0c0cad5cc3d00000000202024594e1d20484a
311302040000000000028ac2d3d3d7ceb3680000000000372c1d3940261d5340
201d0011000000000000086886b5c8bb951b000000000013221b333937244046
241100190000000000000000405d57350000000000000028172a481b0a3b4e2a
19020011000000000000000000000000000000000000001b2c1d283317154235
1d0c000e000000000000000000000000000000000000001b0a22351915314215
15000011000000000000000000000000000000000000002c040c353513113b2c
1b0e00060000000000000000000000004a530e00000019190e2e3d130e2e4011
130000040400000037685100000000224e755b1b00000633080e392a11154820
1b0a021b0400001d575d75240000003d625d33130000202c1311371d002e3d26
190000001d0000152c37423b15000c192a1b1d2a0e0611310c0a263113172a17
1906000422000020190e24330000061d06002224080022131d202e0e242c2e0a
000000001500000a170008110800081108000a2408001122000e1d310c0c2617
1d060000110000060400001300000e1b00000e150000200c000020171b281b20
0000000000000000000000110000041300000c240000112000061b2a000a2219
110400000e00000400000011000004190000170a0000151300001d080019260c
000000000000000a000000130000080e00000c170000111b0a0e1b13060a1b15
110200000a000000040000000000000000000a1100001104000c2400000e220c
00000000000000000000000000000008000000130000130e000e150e04081913
0e0200000000000000000000000000000000000000000c000000220a00001d00
0000000000000000000000110000001100000c0e0404110c020a190e060e170c
0a0200000000000000000000000000000000000000000c000000130800000e04
000000000000000000000000000000150000080a00020e0e0208150a020c130c
max_c=8 max_r=2 max_match=118
 pattern found at 8 2
 x=1072 y=188 z=543
xyzcal_find_point_center2
 x0=1072
 y0=188
 z0=543
   z0=534
OK
 x0=1070
 y0=166
xyzcal_find_point_center2
 x0=1070
 y0=166
 z0=534
   z0=528
OK
 x0=1068
 y0=153
xyzcal_find_point_center2
 x0=1068
 y0=153
 z0=528
   z0=530
OK
 x0=1070
 y0=148
xyzcal_find_point_center2
 x0=1070
 y0=148
 z0=530
   z0=514
OK
 x0=1068
 y0=145
xyzcal_find_point_center2
 x0=1068
 y0=145
 z0=514
   z0=526
OK
 x0=1070
 y0=147
xyzcal_meassure_leave
echo:busy: processing
echo:busy: processing
echo:busy: processing
xyzcal_find_bed_induction_sensor_point_xy x=22000 y=200 z=1726
point=1 x=22000 y=700 z=1726
xyzcal_meassure_enter
xyzcal_searchZ x=22000 y=700 z=1726
xyzcal_spiral8 cx=22000 cy=700 z0=1726 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=22000 cy=700 z0=1726 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=22000 cy=700 z0=1626 dz=100 radius=-900 ad=0
xyzcal_spiral2 cx=22000 cy=700 z0=1526 dz=100 radius=900 ad=3
xyzcal_spiral2 cx=22000 cy=700 z0=1426 dz=100 radius=-900 ad=2
xyzcal_spiral8 cx=22000 cy=700 z0=1326 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=22000 cy=700 z0=1326 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=22000 cy=700 z0=1226 dz=100 radius=-900 ad=0
xyzcal_spiral2 cx=22000 cy=700 z0=1126 dz=100 radius=900 ad=3
xyzcal_spiral2 cx=22000 cy=700 z0=1026 dz=100 radius=-900 ad=2
xyzcal_spiral8 cx=22000 cy=700 z0=926 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=22000 cy=700 z0=926 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=22000 cy=700 z0=826 dz=100 radius=-900 ad=0
xyzcal_spiral2 cx=22000 cy=700 z0=726 dz=100 radius=900 ad=3
xyzcal_spiral2 cx=22000 cy=700 z0=626 dz=100 radius=-900 ad=2
 ON-SIGNAL at x=21690 y=-51 z=617 ad=2236
sizeof(block_buffer)=1392
sizeof(total)=1080
xyzcal_scan_pixels_32x32 cx=22000 cy=700 min_z=545 max_z=2400
000a0000000a00000000000000000000002c4135190000000a00000000000000
081100000c0e0000000000000000000000000000000000000000000000000000
111c0c10110c0000000000000000000000000000000000000000000000000000
1c171313190000000000000b232a260b00000000000000000000000000000000
1f2c14121209000000043c5454635a4221000000000000000000000000000000
141a171612000000012a525a666d616355190000000000000000000000000000
1c290f1216090000275e6069665d5c6a5c260000000000000000000000000000
1620151011120003275263635b4d566562430500000000000000000000000000
19260d11180a0005425a625a525958595b380200000000000000000000000000
1c1c0c0e1a0800000f495c635e515b685b360000000000000000000000000000
1a150c0f11070000023d565d5f67655a45170000000000000000000000000000
181a0c0c0d000000000228465d5a4f4a38030000000000000000000000000000
161f0d0e0b0000000000001d292f290e00000000000000000000000000000000
1a150a0d06000000000000000000000000000000000000000000000000000000
101f0b000b000000000000000000000000000000000000000000000000000000
1117070207000000000000000000000000000000000000000000000000000000
0e1d01080a000000000000000000000000000000000000000000000000000000
1917000a0a000000000a11140a140a0000000000000000000000000000000000
141b0000100600000c150c0000000000000000001f2423000000000000000000
110e00090d0000001209000000000000000000002138320f0000000000000000
120f0000131000000a070000072119090000000f2a25190e0000000000000000
0f110000100c00120a0000001a3943341100000c141814000000000000000000
101506000f1102080b0a001c3849413019000011130400000000000000000000
0f0b00090c00000614000013202930301a0008120a0000000000000000000000
0e0c000010100000120c000f191a101212060010120400000000000000000000
0c0600070e0700080c00000a1400080e09000813070000000000000000000000
0e1502000c0c00000c09000c1008000f0e0500180c0000000000000000000000
000000000f0400080f0000030800000a08000012080000000000000000000000
0d0d020000000000000000071400000a130505170e0000000000000000000000
000000000a0000080b0004101000000c08000013080000000000000000000000
0d080000000000000c0000051400000c1106000e0e0000000000000000000000
0000000000000000000000020800000b07000113040000000000000000000000
  0 811
  1 112
  2 25
  3 14
  4 13
  5 31
  6 18
  7 0
  8 0
  9 0
 10 0
 11 0
 12 0
 13 0
 14 0
 15 0
max_c=112 max_l=1
 min=8 max=128 dif=120
00040000000400000000000000000000004c7960240000000400000000000000
00130000080c0000000000000000000000000000000000000000000000000000
132a081113080000000000000000000000000000000000000000000000000000
2a20171724000000000000063948400600000000000000000000000000000000
314c19151502000000006ea2a2c2ae7b35000000000000000000000000000000
1926201d1500000000489daec8d7bdc2a4240000000000000000000000000000
2a460e151d02000042b7bbcec8b5b3d1b3400000000000000000000000000000
1d331b1113150000429dc2c2b193a6c6c07d0000000000000000000000000000
24400a13220400007baec0ae9dacaaacb1660000000000000000000000000000
2a2a080c260000000e8ab3c2b79bb1ccb1620000000000000000000000000000
261b080e130000000071a6b5b9cac6ae82200000000000000000000000000000
222608080a00000000004484b5ae978c66000000000000000000000000000000
1d310a0c060000000000002c4653460c00000000000000000000000000000000
261b040a00000000000000000000000000000000000000000000000000000000
1131060006000000000000000000000000000000000000000000000000000000
1320000000000000000000000000000000000000000000000000000000000000
0c2c000004000000000000000000000000000000000000000000000000000000
2420000404000000000413190419040000000000000000000000000000000000
1928000011000000081b08000000000000000000313b39000000000000000000
130c00020a0000001502000000000000000000003566590e0000000000000000
150e00001711000004000000003524020000000e483d240c0000000000000000
0e130000110800150400000026687d5d13000008192219000000000000000000
111b00000e1300000604002a668a795524000013170000000000000000000000
0e06000208000000190000173346555526000015040000000000000000000000
0c080000111100001508000e2426111515000011150000000000000000000000
080000000c000000080000041900000c02000017000000000000000000000000
0c1b000008080000080200081100000e0c000022080000000000000000000000
000000000e0000000e0000000000000400000015000000000000000000000000
0a0a0000000000000000000019000004170000200c0000000000000000000000
0000000004000000060000111100000800000017000000000000000000000000
0a0000000000000008000000190000081300000c0c0000000000000000000000
0000000000000000000000000000000600000017000000000000000000000000
max_c=7 max_r=2 max_match=120
 pattern found at 7 2
 x=21808 y=188 z=617
xyzcal_find_point_center2
 x0=21808
 y0=188
 z0=617
   z0=603
OK
 x0=21819
 y0=175
xyzcal_find_point_center2
 x0=21819
 y0=175
 z0=603
   z0=600
OK
 x0=21826
 y0=168
xyzcal_find_point_center2
 x0=21826
 y0=168
 z0=600
   z0=593
OK
 x0=21829
 y0=165
xyzcal_find_point_center2
 x0=21829
 y0=165
 z0=593
   z0=583
OK
 x0=21832
 y0=164
xyzcal_find_point_center2
 x0=21832
 y0=164
 z0=583
   z0=582
OK
 x0=21834
 y0=164
xyzcal_meassure_leave
echo:busy: processing
echo:busy: processing
xyzcal_find_bed_induction_sensor_point_xy x=22000 y=19400 z=1782
point=2 x=22000 y=19800 z=1782
xyzcal_meassure_enter
xyzcal_searchZ x=22000 y=19800 z=1782
xyzcal_spiral8 cx=22000 cy=19800 z0=1782 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=22000 cy=19800 z0=1782 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=22000 cy=19800 z0=1682 dz=100 radius=-900 ad=0
xyzcal_spiral2 cx=22000 cy=19800 z0=1582 dz=100 radius=900 ad=3
xyzcal_spiral2 cx=22000 cy=19800 z0=1482 dz=100 radius=-900 ad=2
xyzcal_spiral8 cx=22000 cy=19800 z0=1382 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=22000 cy=19800 z0=1382 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=22000 cy=19800 z0=1282 dz=100 radius=-900 ad=0
xyzcal_spiral2 cx=22000 cy=19800 z0=1182 dz=100 radius=900 ad=3
xyzcal_spiral2 cx=22000 cy=19800 z0=1082 dz=100 radius=-900 ad=2
xyzcal_spiral8 cx=22000 cy=19800 z0=982 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=22000 cy=19800 z0=982 dz=100 radius=900 ad=0
xyzcal_spiral2 cx=22000 cy=19800 z0=882 dz=100 radius=-900 ad=0
xyzcal_spiral2 cx=22000 cy=19800 z0=782 dz=100 radius=900 ad=3
 ON-SIGNAL at x=21918 y=20589 z=693 ad=2088
sizeof(block_buffer)=1392
sizeof(total)=1080
xyzcal_scan_pixels_32x32 cx=22000 cy=19800 min_z=621 max_z=2400
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0b160a0000000000000000000000000000000000000000000000000000000000
eff5ecccbf9d8c79542402000000000000000000000000000000000000000000
ffffffffffffffffffeeb1712f00000000000000000000000000000000000000
ffffffffffffffffffffffffe4a4642400000000000000000000000000000000
fffffffffffffffffffffffffed4945d3e030000000000000000000000000000
fffffffffffffffffffffffffffffffccc8c4c0f000000000000000000000000
fffffffffffffffffffffffffffeda938a5a3600000000000000000000000000
  0 929
  1 1
  2 3
  3 2
  4 1
  5 3
  6 1
  7 2
  8 3
  9 3
 10 1
 11 2
 12 2
 13 2
 14 4
 15 65
max_c=65 max_l=15
 min=0 max=128 dif=128
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
162c140000000000000000000000000000000000000000000000000000000000
fffffffffffffff2a84804000000000000000000000000000000000000000000
ffffffffffffffffffffffe25e00000000000000000000000000000000000000
ffffffffffffffffffffffffffffc84800000000000000000000000000000000
ffffffffffffffffffffffffffffffba7c060000000000000000000000000000
ffffffffffffffffffffffffffffffffffff981e000000000000000000000000
ffffffffffffffffffffffffffffffffffb46c00000000000000000000000000
max_c=0 max_r=0 max_match=0
xyzcal_meassure_leave

**Comment by Prusa-Support** [comment] 2022-05-20 17:11
Hello! I am sorry for intervening on this thread so late. Given the version of the firmware mentioned and the long time passed, I believe this has been completely solved with the newer firmware versions released in the meantime. Based on this, I'll close the issue - of course, in case anyone is still experiencing issues related with this aspect, do not hesitate to let me know via email info@prusa3d.com mentioning me ("attn: Alessandro"). 

Alessandro Pantaleo
Prusa Research

**Closed as completed by Prusa-Support** 2022-05-20 17:11 UTC
