### ISSUE TITLE
[BUG]<Printer counter>

### ISSUE THREAD

**Issue by zbkingCZ** [prusa3d/Prusa-Firmware#4257] opened 2023-07-03 18:59 UTC
**Printer type** - Original Prusa i3 MK3S+
**Printer firmware version** - 3.12.2
**Printer FW build** - 5713

**MMU upgrade** - No
**MMU upgrade firmware version** - None

**SD card or USB/Octoprint:**
  Prusa Connect

**Describe the bug:**
The number of hours printed and filament lengths on my printer do not agree with the records I make after each maintenance. According to my maintenance records, I only printed about 20 hours between 5/20/2023 and 7/1/2023. So I manually added up the times from the history in Prusa Connect, I counted 173 hours!
I printed a 3.5-hour model today. So I took a picture of the state of the counter before and after printing. The difference on the counter is only 8 minutes and 6 cm of filament after printing.
I print directly from Prusa Slicer 2.6. (previously 2.5.2) and the printer is connected to the Raspberry PI 4 via a USB cable (RPI Port - disabled).
I have not tried printing from the SD card.

  
**To Reproduce:**
Just print anything.
  
  
**G-code**
I am attaching the model from 2023/07/03.

**Attachments:**

**Before Printing:**

![Before printin 030723](https://github.com/prusa3d/Prusa-Firmware/assets/29282782/f17bc56a-b1da-4d45-b433-6d76b6f633fa)

**Printing Model:**

![Prusa Connect](https://github.com/prusa3d/Prusa-Firmware/assets/29282782/59ab7204-99f3-493b-a9f0-387d4edc3080)

**After Printing:**

![After printing 030723](https://github.com/prusa3d/Prusa-Firmware/assets/29282782/495eab6c-2138-43de-937c-9afe093d6b61)

**My Maintenance Log:**

![01-  udrzba](https://github.com/prusa3d/Prusa-Firmware/assets/29282782/1533cf47-196c-4f31-95ad-e4b6d6b666b9)

**Comment by Prusa-Support** [comment] 2023-09-14 17:22
Thanks for reporting.

An "8m/6cm" discrepancy may find an explanation in incorrectly accounted print preparation processes (loading filament, preheating, leveling - not sure if these processes are recorded) but I may seem to understand you noticed larger discrepancies.

However, this is a duplicate of issue https://github.com/prusa3d/Prusa-Firmware/issues/2745 and will be closed as such.
Please collect your further observations in the already existing thread.

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2023-09-14 17:22 UTC
Labels: bug
