### ISSUE TITLE
Y axis crashes

### ISSUE THREAD

**Issue by jemarro12** [prusa3d/Prusa-Firmware#4056] opened 2023-02-28 20:25 UTC
Printer shows random y axes crashes during print.
It can show up to 15 fails/hour.
Fail starts triggering always after 1 hour printing time...
With crash detection turned off any problem.

FW 3.12.1

**Comment by zxlooong** [comment] 2023-03-01 15:23
me too

**Comment by praetorianguards** [comment] 2023-03-13 06:49
+1

**Comment by jemarro12** [comment] 2023-03-13 09:38
Discarded any kinematic/lubrication issue, my problem is still there.
If crash detect disabled it prints flawlessly, during printing at the moment I turn on crash detection it starts triggering several crashes and autohome as it should do...
Any solve??
Any info u need???

**Comment by ParCan** [comment] 2023-04-05 16:43
Me as well.
Always at the same point in the bed travel.
Y axis detects a crash. Homes the nozzle and restarts where it left off
Firmware 3.12.2
Y stripped, Cleaned and lubricated. It's totally free with no tight spots or play
Self tests OK.
Belt tests OK.
![image](https://user-images.githubusercontent.com/989313/230147932-4ce1d2e3-ec22-4b08-87f4-ba4d038e7828.png)
No issues before the FW Upgrade.

**Comment by Prusa-Support** [comment] 2023-04-08 14:36
Thanks for reaching us.

Please allow me to close this issue as duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/2653.
You can monitor the other issue and take part in the discussion.

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2023-04-08 14:36 UTC
