### ISSUE TITLE
Add option to turn off displaying file name while printing from SD card

### ISSUE THREAD

**Issue by Denarian** [prusa3d/Prusa-Firmware#1729] opened 2019-04-13 19:40 UTC
Displaying file name is preventing M117 from working while printing from SD card. It would be nice if it would be an option to turn this feature off

**Comment by mkbel** [comment] 2019-04-14 17:55
Is duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/1443

**Closed as completed by mkbel** 2019-04-14 17:55 UTC
Labels: duplicate
