### ISSUE TITLE
3.2.0-RC1 the PINDA probe triggers off center to the back and left of the probe bed points during XYZ calibration

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#639] opened 2018-04-16 20:49 UTC
3.2.0-RC1 the PINDA probe triggers off center to the back and left of the probe bed points during XYZ calibration **which then shows the bed off skew**.

**Comment by MarekC3D** [comment] 2018-04-17 11:58
Algorithm of calibration point is completely redesigned in 3.2.0. Now points are searched using spiral trajectory. PINDA probe now make a "picture" of calibration point (and space around) that is then processed by Rambo board. During out tests this algorithm is more precise and faster.

**Comment by Crunch69** [comment] 2018-04-17 18:34
MarekC3D the new calibration is incorrectly triggering off center of the calibration points and creates and off skew situation

**Comment by stahlfabrik** [comment] 2018-04-17 19:46
The problem is the z downward motion where the pinda is supposed to be in the middle of the pcb circles: it is not in the middle anymore, triggering late or not at all. 

It has nothing to do with what follows next, the new algorithm

**Comment by stahlfabrik** [comment] 2018-04-17 19:47
Imho - as i have not opened this issue

**Comment by PavelSindler** [comment] 2018-04-18 14:29
This seems to be related to issue https://github.com/prusa3d/Prusa-Firmware/issues/637 We are working on it. Thanks for reporting.

**Comment by Prusa-Support** [comment] 2022-05-12 08:35
The issue has been fixed in newer firmwares.

Marina Curzi
Prusa Research

**Closed as completed by Prusa-Support** 2022-05-12 08:35 UTC
