### ISSUE TITLE
Feature Request: No beep on manual filament unload

### ISSUE THREAD

**Issue by tuxmobil** [prusa3d/Prusa-Firmware#682] opened 2018-04-27 12:58 UTC
With the upgrade to MK2.5 the printer has the new habit of waking my neighbors with a loud beep after manually unloading the filament. While I agree that a beep (although cancelable by the user) might be a good idea in case of an error, I think it should not beep on any manual interaction on which I'm following the printer's actions anyways. Or at least make it optional.

**Comment by vaxxi** [comment] 2018-04-27 13:12
https://github.com/prusa3d/Prusa-Firmware/issues/478

**Comment by Prusa-Support** [comment] 2022-05-13 08:47
Duplicate of [#478](https://github.com/prusa3d/Prusa-Firmware/issues/478).

Marina Curzi
Prusa Research

**Closed as completed by Prusa-Support** 2022-05-13 08:47 UTC
