### ISSUE TITLE
[BUG]Division by zero with "M900 K15"

### ISSUE THREAD

**Issue by smurfix** [prusa3d/Prusa-Firmware#2570] opened 2020-04-01 13:14 UTC
**Printer type** - MK3S
**Printer firmware version**-  current MK3 master

**Describe the bug**

This code results in `new_K` =0 when `k<=15`. This later results in a division-by-zero error and a printer reboot.

```
  // Approximate a LA10 value to a LA15 equivalent.
static float la10c_convert(float k)
{
    float new_K = k * 0.004 - 0.06;
    return (new_K < 0? 0: new_K);
}
```

**To Reproduce**
Print with `M900 K=16`. Works. Now print with `K=15`. Crash.

**Comment by wavexx** [comment] 2020-04-01 14:44
Did you find this by chance during a test of because you happened to use a K value below 15 with some material?

**Comment by wavexx** [comment] 2020-04-01 22:52
I'm looking at this along with #2566. Do you have a short gcode that makes the print crash/reboot? I'd love to add this as a test case.

**Comment by smurfix** [comment] 2020-04-02 07:20
I am printing with a 0.8mm nozzle and noticed splodged bottom infill at the edges even when the overlap is set to zero. The gcode that comes with PrusaSlicer reduces K to 18 when the nozzle is set to 0.6 so I tried with 15, which then crashed before emitting a single blob of filament. Editing the gcode to K=16 rescued the print but still has a bit too much infill.

Thus I assume that basically any print will die when you set K=15.

**Comment by wavexx** [comment] 2020-04-02 11:01
> Thus I assume that basically any print will die when you set K=15.

Not always. Note that the entire range down to K=0 is actually a legitimate value for LA. There is a problem later on that can cause either a zero division or (in case of the other issue) excessive loss of precision, but it also depends on the segment at hand.

I can reproduce nicely the issue in #2566 but couldn't get a crash right away

**Comment by smurfix** [comment] 2020-04-02 11:49
OK. I'll try to recreate the offending file.

**Comment by vintagepc** [comment] 2020-04-06 01:44
Just to clarify here... you are setting `M900 K15` right? Not `M900 K**=**15`? I ask because of the quotes in the title. `K=15` is not valid gcode.

**Comment by smurfix** [comment] 2020-04-06 06:34
Yes, M900 K15, sorry.

**Comment by UltiCa** [comment] 2020-04-11 15:40
I have the same problem with M900 K15 on my Prusa. I do not know, if there is a division by zero problem, but if I set M900 K15 (M900 K30 is running quite well), then next command cashes the Prusa (MK3S with MMU2S and 3.8.1). He does nothing, the display is frozen 1-2-3 seconds later the Prusa reboots.

; generated by PrusaSlicer 2.2.0+ on 2020-04-02 at 10:05:34 UTC
; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm
; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm
M73 P0 R117
M73 Q0 S117
M201 X1000 Y1000 Z1000 E8000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M862.3 P "MK3SMMU2S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.8.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S230 ; set extruder temp
M140 S85 ; set bed temp
M190 S85 ; wait for bed temp
M109 S230 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
; Send the filament type to the MMU2.0 unit.
; E stands for extruder number, F stands for filament type (0: default; 1:flex; 2: PVA)
M403 E0 F0
M403 E1 F0
M403 E2 F0
M403 E3 F0
M403 E4 F0
;go outside print area
G1 Y-3.0 F1000.0
G1 Z0.4 F1000.0
; select extruder
T0
; initial load
G1 X55.0 E29.0 F1073.0
M73 Q0 S117
M73 P0 R117
G1 X5.0 E29.0 F1800.0
G1 X55.0 E8.0 F2000.0
G1 Z0.3 F1000.0
G92 E0.0
G1 X240.0 E25.0 F2200.0
G1 Y-2.0 F1000.0
G1 X55.0 E25 F1400.0
G1 Z0.20 F1000.0
G1 X5.0 E4.0 F1000.0
G92 E0.0
M221 S95
G92 E0.0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
T0
M900 K15 ; Filament gcode
G1 Z0.200 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2
G1 E-1.40000 F2100.00000
G1 Z0.400 F10800.000
;AFTER_LAYER_CHANGE
;0.2
G1 E-1.60000 F2100.00000
G1 X104.685 Y126.881 F10800.000
G1 Z0.200
G1 E3.00000 F2100.00000
;-------------------------------------
; CP WIPE TOWER FIRST LAYER BRIM START

**Comment by wavexx** [comment] 2020-04-11 16:08
Are you using the latest beta (3.9.0 RC1) or the latest release (3.8.1)?

**Comment by smurfix** [comment] 2020-04-19 10:18
@wavexx  Umm, neither. I wrote "current master". At that time that was commit e481013.

**Comment by wavexx** [comment] 2020-04-19 11:01
The latest fixes for LA got merged on friday, this should be now fixed in master

**Closed as completed** 2020-09-21 06:38 UTC
Labels: bug
