### ISSUE TITLE
[FEATURE REQUEST] Support M486 - Cancel Objects

### ISSUE THREAD

**Issue by davidosterberg** [prusa3d/Prusa-Firmware#2880] opened 2020-11-01 13:22 UTC
Please consider supporting the [M486 CancelObjects](https://marlinfw.org/docs/gcode/M486.html) command, supported by the Marlin firmware.  This would allow something like the Octoprint cancel objects command [Octoprint cancel objects command](https://www.youtube.com/watch?v=ANfOr2F79LQ) but without the hazzle of setting up Octoprint.

This feature would be very useful when doing multipart prints and one instance fails.

The support is currently lacking in PrusaSlicer: https://github.com/prusa3d/PrusaSlicer/issues/3279
But it is already now possible to get the command into the g-code by means of  a post-processing script described in the issue.

What I would like is that the firmware offers a cancel object option from the print info screen on the printer. 

The Marlin PR could perhaps be ported easily? https://github.com/MarlinFirmware/Marlin/pull/15590

**Comment by Prusa-Support** [comment] 2023-06-22 19:54
Thanks for the input.
This issue is a duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/2284 and will be closed as that.

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2023-06-22 19:54 UTC
Labels: feature request
