### ISSUE TITLE
manual live-z entry in HW Setup for steel sheets

### ISSUE THREAD

**Issue by draeath** [prusa3d/Prusa-Firmware#2174] opened 2019-09-06 19:46 UTC
Relying on first-layer calibration for this is a bit irritating for experienced users, as the printed pattern for this is not very great. It would be nice if this menu selection branched, allowing us to either run first-layer calibration or manually enter a live-Z adjust setting.

The first-layer calibration in this menu also presumes we have and want to load PLA (see also #262 from 2017 asking that we be able to set temperature for first-layer calibration, which would be even more important now.)

**Comment by leptun** [comment] 2019-09-08 00:04
Duplicate of #2091

**Closed as completed** 2019-09-08 00:42 UTC
