### ISSUE TITLE
MK3 - Einsy compilation 3.2.0-RC1 - printer or motherboard changed

### ISSUE THREAD

**Issue by MarcJenningsUK** [prusa3d/Prusa-Firmware#627] opened 2018-04-14 14:21 UTC
Flashed the firmware from April 13 Einsy version on my MK3.  Now each reboot prompts me that "both printer type and motherboard type changed."

See images at https://www.facebook.com/groups/Prusai3users/permalink/915695925281556/
dOWNLOADED FW LINK - https://github.com/prusa3d/Prusa-Firmware/releases/download/v3.2.0-RC1/prusa3d_fw-3.2.0-RC1.461-1_75mm_MK3-EINSy10a-E3Dv6full.hex

**Comment by stahlfabrik** [comment] 2018-04-14 14:46
Yes I have the same warning here! I did a factory reset after the warning and started all over. After doing the PID tuning and a reset (reboot!) the warning message came again!

**Comment by mvasilakis** [comment] 2018-04-14 14:49
Same.
Using OctoPrint version 1.3.6 stable.

**Comment by Jacks3DPrinting** [comment] 2018-04-14 14:56
same here. But only if my laptop is connected.

**Comment by MarcJenningsUK** [comment] 2018-04-14 15:01
Worth noting in the light of Jacks3DPrinting's comment that I have a Raspberry Pi runing Octopi permanently connected.

**Comment by Jacks3DPrinting** [comment] 2018-04-15 13:20
i also get the message when i hit the rest button.

**Comment by PavelSindler** [comment] 2018-04-16 09:41
We implemented this new function (storing printer and motherboard version to eeprom) recently to MK2.5 firmware. This function was necessary, because we have more and more printer versions and our versioning system for eeprom versions would became too complicated without this. It can also inform user in some cases that he has flashed wrong fw version. This function was already in all MK2.5 firmware versions and there were no issues with it. However it seems that merging it to MK3 caused this bug. Unfortunatly we haven't seen this during testing. We will look on it and fix this as soon as possible. Thank you for your feedback.

**Comment by HFMan** [comment] 2018-04-17 19:40
I don't have this issue on 3.2.0 RC1.  I have a Raspberry Pi 3 B+ connected via USB, pressing reset button on the Prusa produces normal expected behavior.  I only got this message on the first boot after putting RC1 on the Prusa.

**Comment by Crunch69** [comment] 2018-04-19 00:44
yes this occurred when going from fw3.1.3 to 3.2.0 only if i did not erase all data before upgrading

**Comment by magkopian** [comment] 2018-04-23 08:59
Same here, since I updated to 3.2.0-RC1 I get this warning every time I turn on my MK3. Apart from that though everything appears to be working just fine, so I didn't attempt redoing the printer calibration.

**Comment by Prusa-Support** [comment] 2022-05-12 09:02
The issue has been fixed in later releases of the firmware.

Marina Curzi
Prusa Research

**Closed as completed by Prusa-Support** 2022-05-12 09:02 UTC
